/**
 * layers/uy/igm.js — Capas del IGM Uruguay
 *
 * Instituto Geográfico Militar — https://sig.igm.gub.uy/geoserver/wfs
 * Un único WFS en /geoserver/wfs sirve todos los workspaces.
 *
 * Convenciones:
 *  - Keys con sufijo de país para consistencia entre países.
 *  - special: false            → capa general de uso público
 *  - special: 'historico'      → datos de períodos pasados
 *  - special: 'cartografico'   → grillas, geodesia, gravimetría, nivelación
 *  - special: 'catastral'      → parcelas, nomenclatura catastral
 *  - special: 'administrativo' → regionalizaciones internas de organismos
 *  - special: 'auxiliar'       → capas de soporte sin valor semántico directo
 *  - special: 'operacional'    → datos de concesionarias, contratos activos
 *  - special: 'tecnico'        → datos sectoriales de uso restringido
 *  - special: 'raster'         → MDT, MDE, modelos de elevación
 *  - visible: true  → se muestra por defecto en el catálogo de la UI
 *  - visible: false → disponible para el LLM, oculta en la UI por defecto
 *
 *  Regla: special:false implica visible:true, salvo excepciones documentadas.
 *  - titulo y keywords en español — llm.js traduce al idioma del usuario.
 */

export const IGM_UY = {

  // ── División político-administrativa ──────────────────────────────────────────
  departamento_uy: {
    source:        'igm_uy',
    srs:           'EPSG:4326',
    idioma:        'es',
    typename:      'LimitesDepartamentalesA:LimitesDepartamentalesA',
    featureCount:  21,
    vertexCount:   1324850,
    fileSizeKb:    35948,
    titulo:        'Limites Departamentales A',
    tituloEs:      'Limites Departamentales A',
    tituloEn:      'Department',
    tituloPt:      'Departamento',
    tituloUI:      'Departamentos de Uruguay',
    tituloUIEs:    'Departamentos de Uruguay',
    tituloUIEn:    'Departments of Uruguay',
    tituloUIPt:    'Departamentos do Uruguai',
    abstract:      'Limites departamentales mantenidos y actualizados por la división Geodesia y Topografía en conformidad con las leyes vigentes.',
    geomType:      'polygon',
    labelField:    'depto',
    clipStrategy:  'spatial',
    mask:          true,
    special:       false,
    visible:       true,
    keywords:      ['departamento', 'departamentos', 'división política', 'límite departamental', 'uruguay', 'isla brasileña (contestada)', 'rincón de maneco (contestado)'],
    keywordsEs:    ['departamento', 'departamentos', 'división política', 'límite departamental', 'uruguay'],
    keywordsEn:    ['department', 'province', 'political division', 'uruguay'],
    keywordsPt:    ['departamento', 'província', 'divisão política', 'uruguai'],
    attributes:    [
      { campo: 'codigo', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'depto', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'descripcio', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'def', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'shape_leng', labelEn: '', label: '', tipo: 'decimal', visible: false },
      { campo: 'txt', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'obs', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'fcode', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'acc', labelEn: 'Horizontal Accuracy Category', label: 'Categoría de precisión horizontal', tipo: 'int', visible: false },
      { campo: 'use_', labelEn: '', label: '', tipo: 'int', visible: false },
      { campo: 'shape_stle', labelEn: '', label: '', tipo: 'decimal', visible: false },
      { campo: 'globalid_1', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'sde_state_id', labelEn: '', label: '', tipo: 'long', visible: false },
    ],
  },

  municipio_uy: {
    source:        'igm_uy',
    srs:           'EPSG:4326',
    idioma:        'es',
    typename:      'LimitesMunicipales250:LimitesMunicipales',
    featureCount:  129,
    vertexCount:   442651,
    fileSizeKb:    12072,
    titulo:        'Límites Municipales',
    tituloEs:      'Límites Municipales',
    tituloEn:      'Municipality',
    tituloPt:      'Município',
    tituloUI:      'Municipios de Uruguay',
    tituloUIEs:    'Municipios de Uruguay',
    tituloUIEn:    'Municipalities of Uruguay',
    tituloUIPt:    'Municípios do Uruguai',
    abstract:      'Límites Municipales escala 1:250.000 mantenidas por la división Geodesia y Topografía',
    geomType:      'polygon',
    labelField:    'nombre',
    clipStrategy:  'spatial',
    mask:          true,
    special:       false,
    visible:       true,
    keywords:      ['municipio', 'municipios', 'ciudad', 'localidad', 'división municipal', 'uruguay'],
    keywordsEs:    ['municipio', 'municipios', 'ciudad', 'localidad', 'división municipal'],
    keywordsEn:    ['municipality', 'town', 'city', 'locality', 'uruguay'],
    keywordsPt:    ['município', 'cidade', 'localidade', 'uruguai'],
    attributes:    [
      { campo: 'f_code', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'descriptio', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'ara', labelEn: 'Area', label: 'Área', tipo: 'int', visible: false },
      { campo: 'arh', labelEn: '', label: '', tipo: 'int', visible: true },
      { campo: 'acc', labelEn: 'Horizontal Accuracy Category', label: 'Categoría de precisión horizontal', tipo: 'int', visible: false },
      { campo: 'bst', labelEn: 'Boundary Status', label: 'Estado del límite', tipo: 'int', visible: true },
      { campo: 'codigo', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'nombre', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'poblacion', labelEn: '', label: '', tipo: 'int', visible: true, numeric: true },
      { campo: 'alias', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'cedi', labelEn: '', label: '', tipo: 'int', visible: false },
      { campo: 'cod', labelEn: 'Delineation Known', label: 'Delimitación conocida', tipo: 'string', visible: true },
      { campo: 'use_', labelEn: '', label: '', tipo: 'int', visible: false },
      { campo: 'seccionales', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'txt', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'escala', labelEn: '', label: '', tipo: 'int', visible: false },
      { campo: 'seccionpol', labelEn: '', label: '', tipo: 'int', visible: false },
      { campo: 'areaadmini', labelEn: '', label: '', tipo: 'int', visible: false },
      { campo: 'shape_star', labelEn: '', label: '', tipo: 'decimal', visible: false },
      { campo: 'shape_stle', labelEn: '', label: '', tipo: 'decimal', visible: false },
      { campo: 'shape_leng', labelEn: '', label: '', tipo: 'decimal', visible: false },
      { campo: 'sde_state_id', labelEn: '', label: '', tipo: 'long', visible: false },
    ],
  },

  // ── Administrativo ────────────────────────────────────────────────────────────
  seccion_judicial_uy: {
    source:        'igm_uy',
    srs:           'EPSG:4326',
    idioma:        'es',
    typename:      'SeccionalesJudiciales250:SeccionesJudiciales',
    featureCount:  189,
    vertexCount:   1277356,
    fileSizeKb:    34765,
    titulo:        'Secciones Judiciales',
    tituloEs:      'Secciones Judiciales',
    tituloEn:      'Judicial Section',
    tituloPt:      'Seção Judicial',
    tituloUI:      'Secciones judiciales de Uruguay',
    tituloUIEs:    'Secciones judiciales de Uruguay',
    tituloUIEn:    'Judicial Sections of Uruguay',
    tituloUIPt:    'Seções Judiciais do Uruguai',
    abstract:      'Secciones Judiciales fue creado y mantenido por el IGM, el mismo están dibujado en conformidad con la ley vigente y mantenidos por la división Geodesia y Topografía.',
    geomType:      'polygon',
    labelField:    'numero',
    clipStrategy:  'spatial',
    special:       'administrativo',
    visible:       false,
    keywords:      ['sección judicial', 'secciones judiciales', 'judicial', 'jurisdicción', 'juzgado', 'uruguay'],
    keywordsEs:    ['sección judicial', 'secciones judiciales', 'judicial', 'jurisdicción', 'juzgado'],
    keywordsEn:    ['judicial section', 'court', 'jurisdiction', 'uruguay'],
    keywordsPt:    ['seção judicial', 'tribunal', 'jurisdição', 'uruguai'],
    attributes:    [
      { campo: 'f_code', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'descriptio', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'acc', labelEn: 'Horizontal Accuracy Category', label: 'Categoría de precisión horizontal', tipo: 'int', visible: false },
      { campo: 'bst', labelEn: 'Boundary Status', label: 'Estado del límite', tipo: 'int', visible: false },
      { campo: 'nm3', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'nm4', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'use_', labelEn: '', label: '', tipo: 'int', visible: false },
      { campo: 'txt', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'hoja', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'nam', labelEn: 'Name', label: 'Nombre', tipo: 'string', visible: true },
      { campo: 'localidad', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'depto', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'escala', labelEn: '', label: '', tipo: 'int', visible: false },
      { campo: 'shape_star', labelEn: '', label: '', tipo: 'decimal', visible: false },
      { campo: 'shape_stle', labelEn: '', label: '', tipo: 'decimal', visible: false },
      { campo: 'fid_secjud', labelEn: '', label: '', tipo: 'int', visible: false },
      { campo: 'numero', labelEn: '', label: '', tipo: 'int', visible: true, numeric: true },
      { campo: 'shape_leng', labelEn: '', label: '', tipo: 'decimal', visible: false },
      { campo: 'st_area_shape', labelEn: '', label: '', tipo: 'decimal', visible: false },
      { campo: 'st_perimeter', labelEn: '', label: '', tipo: 'decimal', visible: false },
      { campo: 'sde_state_id', labelEn: '', label: '', tipo: 'long', visible: false },
    ],
  },

  // ── Límites nacionales ────────────────────────────────────────────────────────
  limite_terrestre_uy: {
    source:        'igm_uy',
    srs:           'EPSG:4326',
    idioma:        'es',
    typename:      'LimitesNacionalesTerrestres:LimitesNacionalesTerrestres',
    featureCount:  9,
    vertexCount:   1031,
    fileSizeKb:    31,
    titulo:        'Limites Nacionales Terrestres',
    tituloEs:      'Limites Nacionales Terrestres',
    tituloEn:      'Land Border',
    tituloPt:      'Fronteira Terrestre',
    tituloUI:      'Límites nacionales terrestres de Uruguay',
    tituloUIEs:    'Límites nacionales terrestres de Uruguay',
    tituloUIEn:    'Land Borders of Uruguay',
    tituloUIPt:    'Fronteiras Terrestres do Uruguai',
    abstract:      'Limites Nacionales Terrestre conforme la regulación vigente, estos datos son mantenidos por la división Geodesia y Topografía del IGM',
    geomType:      'line',
    labelField:    'def',
    clipStrategy:  'none',
    special:       false,
    visible:       true,
    keywords:      ['límite', 'límite nacional', 'frontera', 'límite terrestre', 'uruguay', 'cuchilla negra', 'cuchilla santa ana', 'rivera - livramento'],
    keywordsEs:    ['límite', 'límite nacional', 'frontera', 'límite terrestre', 'uruguay'],
    keywordsEn:    ['border', 'land border', 'uruguay'],
    keywordsPt:    ['fronteira', 'fronteira terrestre', 'uruguai'],
    attributes:    [
      { campo: 'def', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'obs', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'fcode', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'acc', labelEn: 'Horizontal Accuracy Category', label: 'Categoría de precisión horizontal', tipo: 'short', visible: false },
      { campo: 'bst', labelEn: 'Boundary Status', label: 'Estado del límite', tipo: 'short', visible: true },
      { campo: 'mn3', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'mn4', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'txt', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'depto', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'loc', labelEn: 'Vertical Relative Location', label: 'Posición vertical relativa', tipo: 'string', visible: true },
      { campo: 'escala', labelEn: '', label: '', tipo: 'short', visible: false },
      { campo: 'hoja', labelEn: '', label: '', tipo: 'decimal', visible: false },
      { campo: 'use_', labelEn: '', label: '', tipo: 'int', visible: false },
      { campo: 'sde_state_id', labelEn: '', label: '', tipo: 'long', visible: false },
    ],
  },

  limite_marino_uy: {
    source:        'igm_uy',
    srs:           'EPSG:4326',
    idioma:        'es',
    typename:      'LimitesNacionalesMarinos250:LimitesNacionalesMarinos',
    featureCount:  26,
    vertexCount:   56176,
    fileSizeKb:    1533,
    titulo:        'Limites Nacionales Marinos',
    tituloEs:      'Limites Nacionales Marinos',
    tituloEn:      'Maritime Border',
    tituloPt:      'Fronteira Marítima',
    tituloUI:      'Límites nacionales marinos de Uruguay',
    tituloUIEs:    'Límites nacionales marinos de Uruguay',
    tituloUIEn:    'Maritime Borders of Uruguay',
    tituloUIPt:    'Fronteiras Marítimas do Uruguai',
    abstract:      'Limites Nacionales Terrestre conforme la regulación vigente, estos datos son mantenidos por la división Geodesia y Topografía del IGM',
    geomType:      'line',
    labelField:    'def',
    clipStrategy:  'none',
    special:       false,
    visible:       true,
    keywords:      ['límite marino', 'límite marítimo', 'mar territorial', 'zona económica exclusiva', 'uruguay', 'arroyo chuy', 'arroyo de la mina', 'arroyo san luis (parte norte)', 'arroyo san luis (parte sur)', 'arroyo san miguel', 'arroyo yaguarón chico', 'cañada del cementerio', 'franja costera y jurisdicción exclusiva', 'isla brasileña (contestada)', 'laguna merín', 'límite del lecho y subsuelo', 'límite exterior del río de la plata', 'límite exterior mar terriorial', 'límite exterior zona contigua', 'límite lateral marítimo', 'límite lateral marítimo brasil - uruguay', 'rincón de maneco (contestado)', 'río yaguarón (bajo yaguarón)', 'río yaguarón (yaguarón medio)', 'traza del río uruguay', 'álveo río cuareim'],
    keywordsEs:    ['límite marino', 'límite marítimo', 'mar territorial', 'zona económica exclusiva', 'uruguay'],
    keywordsEn:    ['maritime border', 'exclusive economic zone', 'uruguay'],
    keywordsPt:    ['fronteira marítima', 'zona econômica exclusiva', 'uruguai'],
    attributes:    [
      { campo: 'def', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'obs', labelEn: '', label: '', tipo: 'string', visible: true, classifiable: true },
      { campo: 'fcode', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'acc', labelEn: 'Horizontal Accuracy Category', label: 'Categoría de precisión horizontal', tipo: 'short', visible: false },
      { campo: 'bst', labelEn: 'Boundary Status', label: 'Estado del límite', tipo: 'short', visible: true },
      { campo: 'mn3', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'mn4', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'txt', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'depto', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'loc', labelEn: 'Vertical Relative Location', label: 'Posición vertical relativa', tipo: 'string', visible: true },
      { campo: 'escala', labelEn: '', label: '', tipo: 'short', visible: false },
      { campo: 'hoja', labelEn: '', label: '', tipo: 'decimal', visible: false },
      { campo: 'use_', labelEn: '', label: '', tipo: 'int', visible: false },
      { campo: 'sde_state_id', labelEn: '', label: '', tipo: 'long', visible: false },
    ],
  },

  // ── Hidrografía ───────────────────────────────────────────────────────────────
  rio_area_uy: {
    source:        'igm_uy',
    srs:           'EPSG:4326',
    idioma:        'es',
    typename:      'Hidrografia250:RioArroyoA_250K',
    featureCount:  184,
    vertexCount:   11187,
    fileSizeKb:    382,
    titulo:        'Rio Arroyo A (Escala 250K)',
    tituloEs:      'Rio Arroyo A (Escala 250K)',
    tituloEn:      'River Area',
    tituloPt:      'Área de Rio',
    tituloUI:      'Ríos y arroyos de Uruguay',
    tituloUIEs:    'Ríos y arroyos de Uruguay',
    tituloUIEn:    'Rivers and Streams of Uruguay',
    tituloUIPt:    'Rios e Arroios do Uruguai',
    abstract:      '',
    geomType:      'polygon',
    labelField:    'nam',
    clipStrategy:  'spatial',
    special:       false,
    visible:       true,
    keywords:      ['río', 'ríos', 'arroyo', 'arroyos', 'cañada', 'hidrografía', 'agua', 'cuenca', 'uruguay', 'ao . veras', 'ao. bequeló', 'ao. del ceibo', 'ao. del tala', 'ao. maldonado', 'ao. salsipuedes', 'ao. sarandí de la horqueta', 'ao. solís grande', 'ao. tacuarembó chico', 'ao. tropa vieja', 'ao. yaguarí', 'brazo arapey grande', 'brazo de la fea', 'brazo de la la enramada', 'brazo de las cañas', 'brazo de las conchas', 'brazo de los laureles', 'brazo de los negros', 'brazo de los perros', 'brazo del  achar', 'brazo del  arroyo grande', 'brazo del boycuá', 'brazo del carpintería', 'brazo del espinillar', 'brazo del guayabos', 'brazo del itapebí chico', 'brazo del itapebí grande', 'brazo del laureles', 'brazo del medio', 'brazo del palomas grande', 'brazo del rolón', 'brazo del río yí', 'brazo del salsipuedes grande', 'brazo del san josé', 'brazo del sarandí', 'brazo del sauce', 'brazo del sauce grande', 'brazo del sauzal', 'brazo del tala', 'brazo del tigre', 'brazo del tres árboles', 'cda. marrero', 'océano atlántico', 'río arapey grande', 'río cebollatí', 'río daymán', 'río de la plata', 'río negro', 'río queguay grande', 'río san luis', 'río san salvador', 'río santa lucía', 'río uruguay', 'río uruguay (entero)', 'río yaguarón', 'río yí'],
    keywordsEs:    ['río', 'ríos', 'arroyo', 'arroyos', 'cañada'],
    keywordsEn:    ['river', 'stream', 'uruguay'],
    keywordsPt:    ['rio', 'arroyo', 'uruguai'],
    attributes:    [
      { campo: 'f_code', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'descriptio', labelEn: '', label: '', tipo: 'string', visible: true, classifiable: true },
      { campo: 'nam', labelEn: 'Name', label: 'Nombre', tipo: 'string', visible: true },
      { campo: 'hyc', labelEn: '', label: '', tipo: 'int', visible: true },
      { campo: 'exs', labelEn: '', label: '', tipo: 'int', visible: true },
      { campo: 'acc', labelEn: 'Horizontal Accuracy Category', label: 'Categoría de precisión horizontal', tipo: 'int', visible: false },
      { campo: 'wid', labelEn: 'Width', label: 'Ancho', tipo: 'int', visible: true, numeric: true },
      { campo: 'tid', labelEn: 'Tide Influenced', label: 'Influenciado por mareas', tipo: 'int', visible: true },
      { campo: 'localidad', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'depto', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'hoja', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'txt', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'escala', labelEn: '', label: '', tipo: 'int', visible: false },
      { campo: 'rioarroyoc', labelEn: '', label: '', tipo: 'int', visible: false },
      { campo: 'rioarroy_2', labelEn: '', label: '', tipo: 'int', visible: false },
      { campo: 'shape_star', labelEn: '', label: '', tipo: 'decimal', visible: false },
      { campo: 'shape_stle', labelEn: '', label: '', tipo: 'decimal', visible: false },
      { campo: 'sde_state_id', labelEn: '', label: '', tipo: 'long', visible: false },
    ],
  },

  rio_linea_uy: {
    source:        'igm_uy',
    srs:           'EPSG:4326',
    idioma:        'es',
    typename:      'Hidrografia250:RioArroyoL_250K',
    featureCount:  6035,
    vertexCount:   93542,
    fileSizeKb:    5029,
    titulo:        'Rio Arroyo L (Escala 250K)',
    tituloEs:      'Rio Arroyo L (Escala 250K)',
    tituloEn:      'River Line',
    tituloPt:      'Linha de Rio',
    tituloUI:      'Ríos y arroyos de Uruguay',
    tituloUIEs:    'Ríos y arroyos de Uruguay',
    tituloUIEn:    'Rivers and Streams of Uruguay',
    tituloUIPt:    'Rios e Arroios do Uruguai',
    abstract:      '',
    geomType:      'line',
    labelField:    'nam',
    clipStrategy:  'spatial',
    dissolveBy:    { field: 'nam', label: 'nombre del río', type: 'string' },
    special:       false,
    visible:       true,
    keywords:      ['río', 'ríos', 'arroyo', 'arroyos', 'cañada', 'hidrografía', 'agua', 'cuenca', 'uruguay', 'ao. agua dulce', 'ao. algarrobos', 'ao. aparicio', 'ao. arazá', 'ao. averías', 'ao. bolas grande', 'ao. bopicua', 'ao. canelón grande', 'ao. carpintería', 'ao. catalán chico', 'ao. catalán grande', 'ao. catalán seco', 'ao. ceballitos', 'ao. ceballos grande', 'ao. ceibal', 'ao. chiflero', 'ao. cochengo', 'ao. colorado chico', 'ao. corral de piedra', 'ao. cuaró chico', 'ao. cuaró grande', 'ao. cueva del tigre', 'ao. curupí', 'ao. de chamangá', 'ao. de florencio', 'ao. de gaspar', 'ao. de la azotea', 'ao. de la casa de piedra', 'ao. de la charqueada', 'ao. de la invernada', 'ao. de la isleta', 'ao. de la perdíz', 'ao. de la piedra sola', 'ao. de la raposa', 'ao. de la tuna', 'ao. de las cañas', 'ao. de las pajas blancas', 'ao. de las palmas', 'ao. de las pavas', 'ao. de lemos', 'ao. de los caraguatás', 'ao. de los ceibos', 'ao. de los juncos', 'ao. de los molles', 'ao. de los molles del sauce', 'ao. de los padres', 'ao. de los perros', 'ao. de melilla', 'ao. de pintos', 'ao. del  arenal chico', 'ao. del  sauce', 'ao. del arbolito', 'ao. del avestruz', 'ao. del bagre', 'ao. del catalancito', 'ao. del colorado', 'ao. del corral de piedra', 'ao. del cortado', 'ao. del descarnado', 'ao. del gato', 'ao. del gigante', 'ao. del horno', 'ao. del medio', 'ao. del miguelete', 'ao. del pedernal chico', 'ao. del pescador', 'ao. del renegado', 'ao. del sarandí', 'ao. del sauce', 'ao. del tala', 'ao. del tigre', 'ao. del totoral', 'ao. don esteban chico', 'ao. duraznito', 'ao. durazno', 'ao. durán', 'ao. falso mandiyú', 'ao. frasquito', 'ao. guaviyú', 'ao. hernández', 'ao. juan fernández', 'ao. juncal', 'ao. la pedrera', 'ao. la rambla', 'ao. lenguazo', 'ao. maletas chico', 'ao. manantiales', 'ao. mandiyú', 'ao. maneco', 'ao. manga', 'ao. molles', 'ao. navarro', 'ao. palma sola grande', 'ao. pantanoso', 'ao. patitas', 'ao. pauni', 'ao. pedregal', 'ao. pelado', 'ao. pichinango', 'ao. piedras de espinosa', 'ao. pilatos', 'ao. pintadito', 'ao. polancos', 'ao. polonia', 'ao. porongos', 'ao. quebracho', 'ao. quintón', 'ao. ramiréz grande', 'ao. retobadas', 'ao. san carlos', 'ao. san gregorio', 'ao. san luis', 'ao. sarandí', 'ao. sarandí chico', 'ao. sauce', 'ao. sauce chico', 'ao. sauce de macedo', 'ao. sauce de pintos', 'ao. sauce grande', 'ao. sepulturas', 'ao. sequeira', 'ao. solís grande', 'ao. talita', 'ao. toribio de la llana', 'ao. tres cruces chico', 'ao. tres cruces grande', 'ao. tres árboles', 'ao. trillo', 'ao. tropa vieja', 'ao. vejigas', 'ao. viraró', 'ao. yacaré chico', 'ao. yacaré grande', 'ao. yacot', 'ao. yucutujá', 'cda. arazá', 'cda. arbolito', 'cda. atolladero', 'cda. atolladora', 'cda. bellaca', 'cda. blanquillo', 'cda. bonilla', 'cda. capivara', 'cda. cardozo', 'cda. clarín', 'cda. colorada', 'cda. cortinas', 'cda. cueva del tigre', 'cda. curupí', 'cda. de anselmo', 'cda. de baldoino', 'cda. de bolivar', 'cda. de eleuterio', 'cda. de hackembruck', 'cda. de la barrera', 'cda. de la canelera', 'cda. de la concha', 'cda. de la divisa', 'cda. de la enramada', 'cda. de la horqueta', 'cda. de la isla', 'cda. de la laguna', 'cda. de la lana', 'cda. de la manga de terrón', 'cda. de la pedrera', 'cda. de la piedra redonda', 'cda. de la pierna de palo', 'cda. de la pulpería', 'cda. de la quinta', 'cda. de la quisilla', 'cda. de la rata', 'cda. de la tapera', 'cda. de la totora', 'cda. de la zanja', 'cda. de la zanja honda', 'cda. de las barrancas negras', 'cda. de las canteras', 'cda. de las chacras', 'cda. de las conchas', 'cda. de las conchillas', 'cda. de las nutrias', 'cda. de las pajas', 'cda. de las piedras', 'cda. de las piedritas', 'cda. de las rosas', 'cda. de los burros', 'cda. de los chachos', 'cda. de los corrales', 'cda. de los fuentes', 'cda. de los manantiales', 'cda. de los negros', 'cda. de los padres', 'cda. de los perros', 'cda. de mendoza', 'cda. de modesto', 'cda. de paraso', 'cda. de pascual', 'cda. de rocha', 'cda. de valdez', 'cda. del balta', 'cda. del bolocuá', 'cda. del capitan', 'cda. del catalán', 'cda. del ceibal', 'cda. del cementerio', 'cda. del cerro', 'cda. del chaná', 'cda. del convoy', 'cda. del guaviyú', 'cda. del horno', 'cda. del indio muerto', 'cda. del juncal', 'cda. del junco', 'cda. del medio', 'cda. del negro', 'cda. del negro paciencia', 'cda. del pedregal', 'cda. del perro muerto', 'cda. del pesquero', 'cda. del portero', 'cda. del rodeo', 'cda. del sarandí', 'cda. del sauce', 'cda. del sauce solo', 'cda. del sauzal', 'cda. del tajamar', 'cda. del tala', 'cda. del tigre', 'cda. del totoral', 'cda. del turumán', 'cda. del viejo sebastián', 'cda. del yacaré', 'cda. del ñandubay seco', 'cda. divisa', 'cda. divisoria pando san jacinto', 'cda. don fidel', 'cda. espinillos', 'cda. feliciano', 'cda. gadea', 'cda. garcía', 'cda. grande', 'cda. honda', 'cda. la barra', 'cda. la lorenza', 'cda. lisboa', 'cda. luzardo', 'cda. machín', 'cda. manantial', 'cda. marrero', 'cda. martínez', 'cda. mataojo', 'cda. medina', 'cda. moreira', 'cda. ojos de agua', 'cda. pajas blancas', 'cda. pantanosa', 'cda. pantanoso', 'cda. pereira', 'cda. piedra del toro', 'cda. piedras blancas', 'cda. prudencia', 'cda. sauzal de la divisa', 'cda. sotelo', 'cda. talita', 'cda. uña de gato', 'cda. varela', 'cda. velázquez', 'cda. venezuela', 'cda. vera', 'cda. viraró', 'cda. vázquez', 'cda. yacaré', 'gajo del sarandí', 'zja. aguapey', 'zja. carpinchos', 'zja. de la cerrillada', 'zja. de la estancia', 'zja. de la media luna', 'zja. de la totora', 'zja. de las orejanas', 'zja. de las tunas', 'zja. de los carpinchos', 'zja. de los juncos', 'zja. de los novios', 'zja. de los talas', 'zja. de taboada', 'zja. del ceibo', 'zja. del cerro grande', 'zja. del duraznal', 'zja. del espinillar', 'zja. del potrero', 'zja. del sauce', 'zja. del sauzal grande', 'zja. del tigre', 'zja. fea', 'zja. honda'],
    keywordsEs:    ['río', 'ríos', 'arroyo', 'arroyos', 'cañada'],
    keywordsEn:    ['river', 'stream', 'uruguay'],
    keywordsPt:    ['rio', 'arroyo', 'uruguai'],
    attributes:    [
      { campo: 'f_code', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'descriptio', labelEn: '', label: '', tipo: 'string', visible: true, classifiable: true },
      { campo: 'nam', labelEn: 'Name', label: 'Nombre', tipo: 'string', visible: true },
      { campo: 'hyc', labelEn: '', label: '', tipo: 'int', visible: true },
      { campo: 'exs', labelEn: '', label: '', tipo: 'int', visible: true },
      { campo: 'acc', labelEn: 'Horizontal Accuracy Category', label: 'Categoría de precisión horizontal', tipo: 'int', visible: false },
      { campo: 'wid', labelEn: 'Width', label: 'Ancho', tipo: 'int', visible: true },
      { campo: 'tid', labelEn: 'Tide Influenced', label: 'Influenciado por mareas', tipo: 'int', visible: true },
      { campo: 'localidad', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'depto', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'hoja', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'txt', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'escala', labelEn: '', label: '', tipo: 'int', visible: false },
      { campo: 'tiporio', labelEn: '', label: '', tipo: 'string', visible: true, classifiable: true },
      { campo: 'rioarroyoc', labelEn: '', label: '', tipo: 'int', visible: false },
      { campo: 'shape_stle', labelEn: '', label: '', tipo: 'decimal', visible: false },
      { campo: 'sde_state_id', labelEn: '', label: '', tipo: 'long', visible: false },
    ],
  },

  // ── Históricos ────────────────────────────────────────────────────────────────
  limite_hist_1835_area_uy: {
    source:        'igm_uy',
    srs:           'EPSG:4326',
    idioma:        'es',
    typename:      'Limites_Administrativos_Historicos_A:LimiteA_Ley84_28AGO1835',
    featureCount:  8,
    titulo:        'Limite A Ley 84 - 28 Agosto 1835',
    tituloEs:      'Limite A Ley 84 - 28 Agosto 1835',
    tituloEn:      'Boundary',
    tituloPt:      'Limite',
    tituloUI:      'Límites departamentales históricos 1835 (área)',
    tituloUIEs:    'Límites departamentales históricos 1835 (área)',
    tituloUIEn:    'Historical Departmental Boundaries of Uruguay 1835 (Area)',
    tituloUIPt:    'Limites Departamentais Históricos do Uruguai 1835 (Área)',
    abstract:      '',
    geomType:      'polygon',
    labelField:    'nam',
    clipStrategy:  'none',
    special:       'historico',
    visible:       false,
    keywords:      ['límite histórico', 'departamento histórico', '1835', 'ley 84', 'historia uruguay', 'canelones', 'cerro largo', 'colonia', 'maldonado', 'montevideo', 'paysandú', 'san josé', 'soriano'],
    keywordsEs:    ['límite histórico', 'departamento histórico', '1835', 'ley 84', 'historia uruguay'],
    keywordsEn:    ['historical boundary', 'uruguay history', '1835', 'departmental limits'],
    keywordsPt:    ['limite histórico', 'história uruguai', '1835', 'limites departamentais'],
    attributes:    [
      { campo: 'objectid_1', labelEn: '', label: '', tipo: 'int', visible: false },
      { campo: 'departamen', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'acc', labelEn: 'Horizontal Accuracy Category', label: 'Categoría de precisión horizontal', tipo: 'short', visible: false },
      { campo: 'bst', labelEn: 'Boundary Status', label: 'Estado del límite', tipo: 'short', visible: false },
      { campo: 'use_', labelEn: '', label: '', tipo: 'short', visible: false },
      { campo: 'nm3', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'nm4', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'nam', labelEn: 'Name', label: 'Nombre', tipo: 'string', visible: true },
      { campo: 'localidad', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'escala', labelEn: '', label: '', tipo: 'short', visible: false },
      { campo: 'txt', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'sde_state_id', labelEn: '', label: '', tipo: 'long', visible: false },
    ],
  },

  limite_hist_1835_linea_uy: {
    source:        'igm_uy',
    srs:           'EPSG:4326',
    idioma:        'es',
    typename:      'Limites_Administrativos_Historicos_L:Limite_Ley84_28AGO1835',
    featureCount:  8,
    titulo:        'Limite Ley 84 - 28 Agosto 1835',
    tituloEs:      'Limite Ley 84 - 28 Agosto 1835',
    tituloEn:      'Boundary',
    tituloPt:      'Limite',
    tituloUI:      'Límites departamentales históricos 1835 (línea)',
    tituloUIEs:    'Límites departamentales históricos 1835 (línea)',
    tituloUIEn:    'Historical Departmental Boundaries of Uruguay 1835 (Line)',
    tituloUIPt:    'Limites Departamentais Históricos do Uruguai 1835 (Linha)',
    abstract:      '',
    geomType:      'line',
    labelField:    'def',
    clipStrategy:  'none',
    special:       'historico',
    visible:       false,
    keywords:      ['límite histórico', '1835', 'ley 84', 'historia uruguay', 'canelones', 'cerro largo', 'durazno', 'maldonado', 'montevideo', 'paysandú', 'san josé', 'soriano'],
    keywordsEs:    ['límite histórico', '1835', 'ley 84', 'historia uruguay', 'canelones'],
    keywordsEn:    ['historical boundary', 'uruguay history', '1835', 'departmental limits'],
    keywordsPt:    ['limite histórico', 'história uruguai', '1835', 'limites departamentais'],
    attributes:    [
      { campo: 'def', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'obs', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'fcode', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'use_', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'acc', labelEn: 'Horizontal Accuracy Category', label: 'Categoría de precisión horizontal', tipo: 'short', visible: false },
      { campo: 'bst', labelEn: 'Boundary Status', label: 'Estado del límite', tipo: 'short', visible: false },
      { campo: 'mn3', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'mn4', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'txt', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'depto', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'loc', labelEn: 'Vertical Relative Location', label: 'Posición vertical relativa', tipo: 'string', visible: false },
      { campo: 'escala', labelEn: '', label: '', tipo: 'short', visible: false },
      { campo: 'hoja', labelEn: '', label: '', tipo: 'decimal', visible: false },
      { campo: 'sde_state_id', labelEn: '', label: '', tipo: 'long', visible: false },
    ],
  },

  limite_hist_1837_area_uy: {
    source:        'igm_uy',
    srs:           'EPSG:4326',
    idioma:        'es',
    typename:      'Limites_Administrativos_Historicos_A:LimiteA_Ley158_14JUN1837',
    featureCount:  11,
    titulo:        'Limite A Ley 158 - 14 Junio 1837',
    tituloEs:      'Limite A Ley 158 - 14 Junio 1837',
    tituloEn:      'Boundary',
    tituloPt:      'Limite',
    tituloUI:      'Límites departamentales históricos 1837 (área)',
    tituloUIEs:    'Límites departamentales históricos 1837 (área)',
    tituloUIEn:    'Historical Departmental Boundaries of Uruguay 1837 (Area)',
    tituloUIPt:    'Limites Departamentais Históricos do Uruguai 1837 (Área)',
    abstract:      '',
    geomType:      'polygon',
    labelField:    'nam',
    clipStrategy:  'none',
    special:       'historico',
    visible:       false,
    keywords:      ['límite histórico', 'departamento histórico', '1837', 'ley 158', 'historia uruguay', 'canelones', 'cerro largo', 'colonia', 'maldonado', 'minas', 'montevideo', 'paysamdú', 'salto', 'san josé', 'soriano', 'tacuarembó'],
    keywordsEs:    ['límite histórico', 'departamento histórico', '1837', 'ley 158', 'historia uruguay'],
    keywordsEn:    ['historical boundary', 'uruguay history', '1837', 'departmental limits'],
    keywordsPt:    ['limite histórico', 'história uruguai', '1837', 'limites departamentais'],
    attributes:    [
      { campo: 'objectid_1', labelEn: '', label: '', tipo: 'int', visible: false },
      { campo: 'departamen', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'acc', labelEn: 'Horizontal Accuracy Category', label: 'Categoría de precisión horizontal', tipo: 'short', visible: false },
      { campo: 'bst', labelEn: 'Boundary Status', label: 'Estado del límite', tipo: 'short', visible: false },
      { campo: 'nm3', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'nm4', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'use_', labelEn: '', label: '', tipo: 'short', visible: false },
      { campo: 'nam', labelEn: 'Name', label: 'Nombre', tipo: 'string', visible: true },
      { campo: 'localidad', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'escala', labelEn: '', label: '', tipo: 'short', visible: false },
      { campo: 'hoja', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'txt', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'sde_state_id', labelEn: '', label: '', tipo: 'long', visible: false },
    ],
  },

  limite_hist_1837_linea_uy: {
    source:        'igm_uy',
    srs:           'EPSG:4326',
    idioma:        'es',
    typename:      'Limites_Administrativos_Historicos_L:Limite_Ley158_14JUN1837',
    featureCount:  12,
    titulo:        'Limite Ley 158 - 14 Junio 1837',
    tituloEs:      'Limite Ley 158 - 14 Junio 1837',
    tituloEn:      'Boundary',
    tituloPt:      'Limite',
    tituloUI:      'Límites departamentales históricos 1837 (línea)',
    tituloUIEs:    'Límites departamentales históricos 1837 (línea)',
    tituloUIEn:    'Historical Departmental Boundaries of Uruguay 1837 (Line)',
    tituloUIPt:    'Limites Departamentais Históricos do Uruguai 1837 (Linha)',
    abstract:      '',
    geomType:      'line',
    labelField:    'def',
    clipStrategy:  'none',
    special:       'historico',
    visible:       false,
    keywords:      ['límite histórico', '1837', 'ley 158', 'historia uruguay', 'canelones', 'cerro largo', 'colonia', 'durazno', 'maldonado', 'minas', 'montevideo', 'paysandú', 'salto', 'san josé', 'soriano', 'tacuarembó'],
    keywordsEs:    ['límite histórico', '1837', 'ley 158', 'historia uruguay', 'canelones'],
    keywordsEn:    ['historical boundary', 'uruguay history', '1837', 'departmental limits'],
    keywordsPt:    ['limite histórico', 'história uruguai', '1837', 'limites departamentais'],
    attributes:    [
      { campo: 'def', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'obs', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'fcode', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'use_', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'acc', labelEn: 'Horizontal Accuracy Category', label: 'Categoría de precisión horizontal', tipo: 'short', visible: false },
      { campo: 'bst', labelEn: 'Boundary Status', label: 'Estado del límite', tipo: 'short', visible: false },
      { campo: 'mn3', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'mn4', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'txt', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'depto', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'loc', labelEn: 'Vertical Relative Location', label: 'Posición vertical relativa', tipo: 'string', visible: false },
      { campo: 'escala', labelEn: '', label: '', tipo: 'short', visible: false },
      { campo: 'hoja', labelEn: '', label: '', tipo: 'decimal', visible: false },
      { campo: 'sde_state_id', labelEn: '', label: '', tipo: 'long', visible: false },
    ],
  },

  limite_hist_1856_area_uy: {
    source:        'igm_uy',
    srs:           'EPSG:4326',
    idioma:        'es',
    typename:      'Limites_Administrativos_Historicos_A:LimiteA_Ley493_10JUL1856',
    featureCount:  12,
    titulo:        'Limite A Ley 493 - 10 Julio 1856',
    tituloEs:      'Limite A Ley 493 - 10 Julio 1856',
    tituloEn:      'Boundary',
    tituloPt:      'Limite',
    tituloUI:      'Límites departamentales históricos 1856 (área)',
    tituloUIEs:    'Límites departamentales históricos 1856 (área)',
    tituloUIEn:    'Historical Departmental Boundaries of Uruguay 1856 (Area)',
    tituloUIPt:    'Limites Departamentais Históricos do Uruguai 1856 (Área)',
    abstract:      '',
    geomType:      'polygon',
    labelField:    'nam',
    clipStrategy:  'none',
    special:       'historico',
    visible:       false,
    keywords:      ['límite histórico', '1856', 'ley 493', 'historia uruguay', 'canelones', 'cerro largo', 'colonia', 'durazno', 'florida', 'maldonado', 'minas', 'paysandú', 'salto', 'san josé', 'soriano', 'tacuarembó'],
    keywordsEs:    ['límite histórico', '1856', 'ley 493', 'historia uruguay', 'canelones'],
    keywordsEn:    ['historical boundary', 'uruguay history', '1856', 'departmental limits'],
    keywordsPt:    ['limite histórico', 'história uruguai', '1856', 'limites departamentais'],
    attributes:    [
      { campo: 'objectid_1', labelEn: '', label: '', tipo: 'int', visible: false },
      { campo: 'departamen', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'acc', labelEn: 'Horizontal Accuracy Category', label: 'Categoría de precisión horizontal', tipo: 'short', visible: false },
      { campo: 'bst', labelEn: 'Boundary Status', label: 'Estado del límite', tipo: 'short', visible: false },
      { campo: 'nm3', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'nm4', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'use_', labelEn: '', label: '', tipo: 'short', visible: false },
      { campo: 'nam', labelEn: 'Name', label: 'Nombre', tipo: 'string', visible: true },
      { campo: 'localidad', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'escala', labelEn: '', label: '', tipo: 'short', visible: false },
      { campo: 'hoja', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'txt', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'sde_state_id', labelEn: '', label: '', tipo: 'long', visible: false },
    ],
  },

  limite_hist_1856_linea_uy: {
    source:        'igm_uy',
    srs:           'EPSG:4326',
    idioma:        'es',
    typename:      'Limites_Administrativos_Historicos_L:Limite_Ley493_10JUL1856',
    featureCount:  13,
    titulo:        'Limite Ley 493 - 10 Julio 1856',
    tituloEs:      'Limite Ley 493 - 10 Julio 1856',
    tituloEn:      'Boundary',
    tituloPt:      'Limite',
    tituloUI:      'Límites departamentales históricos 1856 (línea)',
    tituloUIEs:    'Límites departamentales históricos 1856 (línea)',
    tituloUIEn:    'Historical Departmental Boundaries of Uruguay 1856 (Line)',
    tituloUIPt:    'Limites Departamentais Históricos do Uruguai 1856 (Linha)',
    abstract:      '',
    geomType:      'line',
    labelField:    'def',
    clipStrategy:  'none',
    special:       'historico',
    visible:       false,
    keywords:      ['límite histórico', '1856', 'ley 493', 'historia uruguay', 'canelones', 'cerro largo', 'colonia', 'durazno', 'florida', 'maldonado', 'minas', 'montevideo', 'paysandú', 'salto', 'san josé', 'soriano', 'tacuarembó'],
    keywordsEs:    ['límite histórico', '1856', 'ley 493', 'historia uruguay', 'canelones'],
    keywordsEn:    ['historical boundary', 'uruguay history', '1856', 'departmental limits'],
    keywordsPt:    ['limite histórico', 'história uruguai', '1856', 'limites departamentais'],
    attributes:    [
      { campo: 'def', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'obs', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'fcode', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'use_', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'acc', labelEn: 'Horizontal Accuracy Category', label: 'Categoría de precisión horizontal', tipo: 'short', visible: false },
      { campo: 'bst', labelEn: 'Boundary Status', label: 'Estado del límite', tipo: 'short', visible: false },
      { campo: 'mn3', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'mn4', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'txt', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'depto', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'loc', labelEn: 'Vertical Relative Location', label: 'Posición vertical relativa', tipo: 'string', visible: false },
      { campo: 'escala', labelEn: '', label: '', tipo: 'short', visible: false },
      { campo: 'hoja', labelEn: '', label: '', tipo: 'decimal', visible: false },
      { campo: 'sde_state_id', labelEn: '', label: '', tipo: 'long', visible: false },
    ],
  },

  limite_hist_1880_area_uy: {
    source:        'igm_uy',
    srs:           'EPSG:4326',
    idioma:        'es',
    typename:      'Limites_Administrativos_Historicos_A:LimiteA_Ley1474_7JUL1880',
    featureCount:  13,
    titulo:        'Limite A Ley 1474 - 7 Julio 1880',
    tituloEs:      'Limite A Ley 1474 - 7 Julio 1880',
    tituloEn:      'Boundary',
    tituloPt:      'Limite',
    tituloUI:      'Límites departamentales históricos 1880 (área)',
    tituloUIEs:    'Límites departamentales históricos 1880 (área)',
    tituloUIEn:    'Historical Departmental Boundaries of Uruguay 1880 (Area)',
    tituloUIPt:    'Limites Departamentais Históricos do Uruguai 1880 (Área)',
    abstract:      '',
    geomType:      'polygon',
    labelField:    'nam',
    clipStrategy:  'none',
    special:       'historico',
    visible:       false,
    keywords:      ['límite histórico', '1880', 'ley 1474', 'historia uruguay', 'canelones', 'cerro largo', 'colonia', 'florida', 'maldonado', 'minas', 'montevideo', 'paysandú', 'río negro', 'salto', 'san josé', 'soriano', 'tacuarembó'],
    keywordsEs:    ['límite histórico', '1880', 'ley 1474', 'historia uruguay', 'canelones'],
    keywordsEn:    ['historical boundary', 'uruguay history', '1880', 'departmental limits'],
    keywordsPt:    ['limite histórico', 'história uruguai', '1880', 'limites departamentais'],
    attributes:    [
      { campo: 'objectid_1', labelEn: '', label: '', tipo: 'int', visible: false },
      { campo: 'departamen', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'acc', labelEn: 'Horizontal Accuracy Category', label: 'Categoría de precisión horizontal', tipo: 'short', visible: false },
      { campo: 'bst', labelEn: 'Boundary Status', label: 'Estado del límite', tipo: 'short', visible: false },
      { campo: 'use_', labelEn: '', label: '', tipo: 'short', visible: false },
      { campo: 'escala', labelEn: '', label: '', tipo: 'short', visible: false },
      { campo: 'nm3', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'nm4', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'nam', labelEn: 'Name', label: 'Nombre', tipo: 'string', visible: true },
      { campo: 'localidad', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'txt', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'hoja', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'sde_state_id', labelEn: '', label: '', tipo: 'long', visible: false },
    ],
  },

  limite_hist_1880_linea_uy: {
    source:        'igm_uy',
    srs:           'EPSG:4326',
    idioma:        'es',
    typename:      'Limites_Administrativos_Historicos_L:Limite_Ley1474_7JUL1880',
    featureCount:  15,
    titulo:        'Limite Ley 1474 - 7 Julio 1880',
    tituloEs:      'Limite Ley 1474 - 7 Julio 1880',
    tituloEn:      'Boundary',
    tituloPt:      'Limite',
    tituloUI:      'Límites departamentales históricos 1880 (línea)',
    tituloUIEs:    'Límites departamentales históricos 1880 (línea)',
    tituloUIEn:    'Historical Departmental Boundaries of Uruguay 1880 (Line)',
    tituloUIPt:    'Limites Departamentais Históricos do Uruguai 1880 (Linha)',
    abstract:      '',
    geomType:      'line',
    labelField:    'def',
    clipStrategy:  'none',
    special:       'historico',
    visible:       false,
    keywords:      ['límite histórico', '1880', 'ley 1474', 'historia uruguay', 'canelones', 'cerro largo', 'colonia', 'durazno', 'florida', 'maldonado', 'minas', 'montevideo', 'paysandú', 'rocha', 'río negro', 'salto', 'san josé', 'soriano', 'tacuarembó'],
    keywordsEs:    ['límite histórico', '1880', 'ley 1474', 'historia uruguay', 'canelones'],
    keywordsEn:    ['historical boundary', 'uruguay history', '1880', 'departmental limits'],
    keywordsPt:    ['limite histórico', 'história uruguai', '1880', 'limites departamentais'],
    attributes:    [
      { campo: 'def', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'obs', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'fcode', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'use_', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'acc', labelEn: 'Horizontal Accuracy Category', label: 'Categoría de precisión horizontal', tipo: 'short', visible: false },
      { campo: 'bst', labelEn: 'Boundary Status', label: 'Estado del límite', tipo: 'short', visible: false },
      { campo: 'mn3', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'mn4', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'txt', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'depto', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'loc', labelEn: 'Vertical Relative Location', label: 'Posición vertical relativa', tipo: 'string', visible: false },
      { campo: 'escala', labelEn: '', label: '', tipo: 'short', visible: false },
      { campo: 'hoja', labelEn: '', label: '', tipo: 'decimal', visible: false },
      { campo: 'sde_state_id', labelEn: '', label: '', tipo: 'long', visible: false },
    ],
  },

  limite_hist_1884_area_uy: {
    source:        'igm_uy',
    srs:           'EPSG:4326',
    idioma:        'es',
    typename:      'Limites_Administrativos_Historicos_A:LimiteA_Ley1757_1OCT1884',
    featureCount:  16,
    titulo:        'Limite A Ley 1757 - 1 octubre 1884',
    tituloEs:      'Limite A Ley 1757 - 1 octubre 1884',
    tituloEn:      'Boundary',
    tituloPt:      'Limite',
    tituloUI:      'Límites departamentales históricos 1884 (área)',
    tituloUIEs:    'Límites departamentales históricos 1884 (área)',
    tituloUIEn:    'Historical Departmental Boundaries of Uruguay 1884 (Area)',
    tituloUIPt:    'Limites Departamentais Históricos do Uruguai 1884 (Área)',
    abstract:      '',
    geomType:      'polygon',
    labelField:    'nam',
    clipStrategy:  'none',
    special:       'historico',
    visible:       false,
    keywords:      ['límite histórico', '1884', 'ley 1757', 'historia uruguay', 'artigas', 'canelones', 'cerro largo', 'colonia', 'florida', 'maldonado', 'minas', 'montevideo', 'paysandú', 'rivera', 'río negro', 'salto', 'san josé', 'soriano', 'tacuarembó', 'treinta y tres'],
    keywordsEs:    ['límite histórico', '1884', 'ley 1757', 'historia uruguay', 'artigas'],
    keywordsEn:    ['historical boundary', 'uruguay history', '1884', 'departmental limits'],
    keywordsPt:    ['limite histórico', 'história uruguai', '1884', 'limites departamentais'],
    attributes:    [
      { campo: 'objectid_1', labelEn: '', label: '', tipo: 'int', visible: false },
      { campo: 'departamen', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'acc', labelEn: 'Horizontal Accuracy Category', label: 'Categoría de precisión horizontal', tipo: 'short', visible: false },
      { campo: 'bst', labelEn: 'Boundary Status', label: 'Estado del límite', tipo: 'short', visible: false },
      { campo: 'nm3', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'nm4', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'use_', labelEn: '', label: '', tipo: 'short', visible: false },
      { campo: 'nam', labelEn: 'Name', label: 'Nombre', tipo: 'string', visible: true },
      { campo: 'localidad', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'escala', labelEn: '', label: '', tipo: 'short', visible: false },
      { campo: 'hoja', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'txt', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'sde_state_id', labelEn: '', label: '', tipo: 'long', visible: false },
    ],
  },

  limite_hist_1884_linea_uy: {
    source:        'igm_uy',
    srs:           'EPSG:4326',
    idioma:        'es',
    typename:      'Limites_Administrativos_Historicos_L:Limite_Ley1757_1OCT1884',
    featureCount:  18,
    titulo:        'Limite Ley 1757 - 1 Octubre 1884',
    tituloEs:      'Limite Ley 1757 - 1 Octubre 1884',
    tituloEn:      'Boundary',
    tituloPt:      'Limite',
    tituloUI:      'Límites departamentales históricos 1884 (línea)',
    tituloUIEs:    'Límites departamentales históricos 1884 (línea)',
    tituloUIEn:    'Historical Departmental Boundaries of Uruguay 1884 (Line)',
    tituloUIPt:    'Limites Departamentais Históricos do Uruguai 1884 (Linha)',
    abstract:      '',
    geomType:      'line',
    labelField:    'def',
    clipStrategy:  'none',
    special:       'historico',
    visible:       false,
    keywords:      ['límite histórico', '1884', 'ley 1757', 'historia uruguay', 'artigas', 'canelones', 'cerro largo', 'colonia', 'durazno', 'florida', 'maldonado', 'minas', 'montevideo', 'paysandú', 'rivera', 'rocha', 'río negro', 'salto', 'san josé', 'soriano', 'tacuarembó', 'treinta y tres'],
    keywordsEs:    ['límite histórico', '1884', 'ley 1757', 'historia uruguay', 'artigas'],
    keywordsEn:    ['historical boundary', 'uruguay history', '1884', 'departmental limits'],
    keywordsPt:    ['limite histórico', 'história uruguai', '1884', 'limites departamentais'],
    attributes:    [
      { campo: 'def', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'obs', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'fcode', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'use_', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'acc', labelEn: 'Horizontal Accuracy Category', label: 'Categoría de precisión horizontal', tipo: 'short', visible: false },
      { campo: 'bst', labelEn: 'Boundary Status', label: 'Estado del límite', tipo: 'short', visible: false },
      { campo: 'mn3', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'mn4', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'txt', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'depto', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'loc', labelEn: 'Vertical Relative Location', label: 'Posición vertical relativa', tipo: 'string', visible: false },
      { campo: 'escala', labelEn: '', label: '', tipo: 'short', visible: false },
      { campo: 'hoja', labelEn: '', label: '', tipo: 'decimal', visible: false },
      { campo: 'sde_state_id', labelEn: '', label: '', tipo: 'long', visible: false },
    ],
  },

  limite_hist_1885_area_uy: {
    source:        'igm_uy',
    srs:           'EPSG:4326',
    idioma:        'es',
    typename:      'Limites_Administrativos_Historicos_A:LimiteA_Ley1854_30DIC1885',
    featureCount:  17,
    titulo:        'Limite A Ley 1854 - 30 Diciembre 1885',
    tituloEs:      'Limite A Ley 1854 - 30 Diciembre 1885',
    tituloEn:      'Boundary',
    tituloPt:      'Limite',
    tituloUI:      'Límites departamentales históricos 1885 (área)',
    tituloUIEs:    'Límites departamentales históricos 1885 (área)',
    tituloUIEn:    'Historical Departmental Boundaries of Uruguay 1885 (Area)',
    tituloUIPt:    'Limites Departamentais Históricos do Uruguai 1885 (Área)',
    abstract:      '',
    geomType:      'polygon',
    labelField:    'nam',
    clipStrategy:  'none',
    special:       'historico',
    visible:       false,
    keywords:      ['límite histórico', '1885', 'ley 1854', 'historia uruguay', 'artigas', 'canelones', 'cerro largo', 'colonia', 'florida', 'maldonado', 'minas', 'montevideo', 'paysandú', 'rivera', 'río negro', 'salto', 'san josé', 'soriano', 'tacuarembó', 'treinta y tres'],
    keywordsEs:    ['límite histórico', '1885', 'ley 1854', 'historia uruguay', 'artigas'],
    keywordsEn:    ['historical boundary', 'uruguay history', '1885', 'departmental limits'],
    keywordsPt:    ['limite histórico', 'história uruguai', '1885', 'limites departamentais'],
    attributes:    [
      { campo: 'objectid_1', labelEn: '', label: '', tipo: 'int', visible: false },
      { campo: 'departamen', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'acc', labelEn: 'Horizontal Accuracy Category', label: 'Categoría de precisión horizontal', tipo: 'short', visible: false },
      { campo: 'bst', labelEn: 'Boundary Status', label: 'Estado del límite', tipo: 'short', visible: false },
      { campo: 'nm3', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'nm4', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'use_', labelEn: '', label: '', tipo: 'short', visible: false },
      { campo: 'nam', labelEn: 'Name', label: 'Nombre', tipo: 'string', visible: true },
      { campo: 'localidad', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'escala', labelEn: '', label: '', tipo: 'short', visible: false },
      { campo: 'hoja', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'txt', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'sde_state_id', labelEn: '', label: '', tipo: 'long', visible: false },
    ],
  },

  limite_hist_1885_linea_uy: {
    source:        'igm_uy',
    srs:           'EPSG:4326',
    idioma:        'es',
    typename:      'Limites_Administrativos_Historicos_L:Limite_Ley1854_30DIC1885',
    featureCount:  19,
    titulo:        'Limite Ley 1854 - 30 Diciembre 1885',
    tituloEs:      'Limite Ley 1854 - 30 Diciembre 1885',
    tituloEn:      'Boundary',
    tituloPt:      'Limite',
    tituloUI:      'Límites departamentales históricos 1885 (línea)',
    tituloUIEs:    'Límites departamentales históricos 1885 (línea)',
    tituloUIEn:    'Historical Departmental Boundaries of Uruguay 1885 (Line)',
    tituloUIPt:    'Limites Departamentais Históricos do Uruguai 1885 (Linha)',
    abstract:      '',
    geomType:      'line',
    labelField:    'def',
    clipStrategy:  'none',
    special:       'historico',
    visible:       false,
    keywords:      ['límite histórico', '1885', 'ley 1854', 'historia uruguay', 'artigas', 'canelones', 'cerro largo', 'colonia', 'durazno', 'flores', 'florida', 'maldonado', 'minas', 'montevideo', 'paysandú', 'rivera', 'rocha', 'río negro', 'salto', 'san josé', 'soriano', 'tacuarembó', 'treinta y tres'],
    keywordsEs:    ['límite histórico', '1885', 'ley 1854', 'historia uruguay', 'artigas'],
    keywordsEn:    ['historical boundary', 'uruguay history', '1885', 'departmental limits'],
    keywordsPt:    ['limite histórico', 'história uruguai', '1885', 'limites departamentais'],
    attributes:    [
      { campo: 'def', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'obs', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'fcode', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'use_', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'acc', labelEn: 'Horizontal Accuracy Category', label: 'Categoría de precisión horizontal', tipo: 'short', visible: false },
      { campo: 'bst', labelEn: 'Boundary Status', label: 'Estado del límite', tipo: 'short', visible: false },
      { campo: 'mn3', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'mn4', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'txt', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'depto', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'loc', labelEn: 'Vertical Relative Location', label: 'Posición vertical relativa', tipo: 'string', visible: false },
      { campo: 'escala', labelEn: '', label: '', tipo: 'short', visible: false },
      { campo: 'hoja', labelEn: '', label: '', tipo: 'decimal', visible: false },
      { campo: 'sde_state_id', labelEn: '', label: '', tipo: 'long', visible: false },
    ],
  },

  limite_hist_1927_area_uy: {
    source:        'igm_uy',
    srs:           'EPSG:4326',
    idioma:        'es',
    typename:      'Limites_Administrativos_Historicos_A:LimiteA_Ley8187_15DIC1927',
    featureCount:  17,
    titulo:        'LimiteA Ley 8187 - 15 Diciembre 1927',
    tituloEs:      'LimiteA Ley 8187 - 15 Diciembre 1927',
    tituloEn:      'Boundary',
    tituloPt:      'Limite',
    tituloUI:      'Límites departamentales históricos 1927 (área)',
    tituloUIEs:    'Límites departamentales históricos 1927 (área)',
    tituloUIEn:    'Historical Departmental Boundaries of Uruguay 1927 (Area)',
    tituloUIPt:    'Limites Departamentais Históricos do Uruguai 1927 (Área)',
    abstract:      '',
    geomType:      'polygon',
    labelField:    'nam',
    clipStrategy:  'none',
    special:       'historico',
    visible:       false,
    keywords:      ['límite histórico', '1927', 'ley 8187', 'historia uruguay', 'artigas', 'canelones', 'cerro largo', 'colonia', 'flores', 'florida', 'lavalleja', 'maldonado', 'montevideo', 'paysandú', 'rivera', 'río negro', 'salto', 'san josé', 'soriano', 'tacuarembó', 'treinta y tres'],
    keywordsEs:    ['límite histórico', '1927', 'ley 8187', 'historia uruguay', 'artigas'],
    keywordsEn:    ['historical boundary', 'uruguay history', '1927', 'departmental limits'],
    keywordsPt:    ['limite histórico', 'história uruguai', '1927', 'limites departamentais'],
    attributes:    [
      { campo: 'objectid_1', labelEn: '', label: '', tipo: 'int', visible: false },
      { campo: 'departamen', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'acc', labelEn: 'Horizontal Accuracy Category', label: 'Categoría de precisión horizontal', tipo: 'short', visible: false },
      { campo: 'bst', labelEn: 'Boundary Status', label: 'Estado del límite', tipo: 'short', visible: false },
      { campo: 'use_', labelEn: '', label: '', tipo: 'short', visible: false },
      { campo: 'nm3', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'nm4', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'nam', labelEn: 'Name', label: 'Nombre', tipo: 'string', visible: true },
      { campo: 'escala', labelEn: '', label: '', tipo: 'short', visible: false },
      { campo: 'hoja', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'localidad', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'txt', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'sde_state_id', labelEn: '', label: '', tipo: 'long', visible: false },
    ],
  },

  limite_hist_1927_linea_uy: {
    source:        'igm_uy',
    srs:           'EPSG:4326',
    idioma:        'es',
    typename:      'Limites_Administrativos_Historicos_L:Limite_Ley8187_15DIC1927',
    featureCount:  19,
    titulo:        'Limite Ley 8187 - 15 Diciembre 1927',
    tituloEs:      'Limite Ley 8187 - 15 Diciembre 1927',
    tituloEn:      'Boundary',
    tituloPt:      'Limite',
    tituloUI:      'Límites departamentales históricos 1927 (línea)',
    tituloUIEs:    'Límites departamentales históricos 1927 (línea)',
    tituloUIEn:    'Historical Departmental Boundaries of Uruguay 1927 (Line)',
    tituloUIPt:    'Limites Departamentais Históricos do Uruguai 1927 (Linha)',
    abstract:      '',
    geomType:      'line',
    labelField:    'def',
    clipStrategy:  'none',
    special:       'historico',
    visible:       false,
    keywords:      ['límite histórico', '1927', 'ley 8187', 'historia uruguay', 'artigas', 'canelones', 'cerro largo', 'colonia', 'durazno', 'flores', 'florida', 'lavalleja', 'maldonado', 'montevideo', 'paysandú', 'rivera', 'rocha', 'río negro', 'salto', 'san josé', 'soriano', 'tacuarembó', 'treinta y tres'],
    keywordsEs:    ['límite histórico', '1927', 'ley 8187', 'historia uruguay', 'artigas'],
    keywordsEn:    ['historical boundary', 'uruguay history', '1927', 'departmental limits'],
    keywordsPt:    ['limite histórico', 'história uruguai', '1927', 'limites departamentais'],
    attributes:    [
      { campo: 'def', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'obs', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'fcode', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'use_', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'acc', labelEn: 'Horizontal Accuracy Category', label: 'Categoría de precisión horizontal', tipo: 'short', visible: false },
      { campo: 'bst', labelEn: 'Boundary Status', label: 'Estado del límite', tipo: 'short', visible: false },
      { campo: 'mn3', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'mn4', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'txt', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'depto', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'loc', labelEn: 'Vertical Relative Location', label: 'Posición vertical relativa', tipo: 'string', visible: false },
      { campo: 'escala', labelEn: '', label: '', tipo: 'short', visible: false },
      { campo: 'hoja', labelEn: '', label: '', tipo: 'decimal', visible: false },
      { campo: 'sde_state_id', labelEn: '', label: '', tipo: 'long', visible: false },
    ],
  },

  limite_hist_1934_area_uy: {
    source:        'igm_uy',
    srs:           'EPSG:4326',
    idioma:        'es',
    typename:      'Limites_Administrativos_Historicos_A:LimiteA_RinconDeManeco_10AGO1934',
    featureCount:  17,
    titulo:        'Limite A "Rincon De Maneco" - 10 Agosto 1934',
    tituloEs:      'Limite A "Rincon De Maneco" - 10 Agosto 1934',
    tituloEn:      'Boundary',
    tituloPt:      'Limite',
    tituloUI:      'Límites históricos Rincón de Maneco 1934 (área)',
    tituloUIEs:    'Límites históricos Rincón de Maneco 1934 (área)',
    tituloUIEn:    'Historical Boundaries of Rincón de Maneco, Uruguay 1934 (Area)',
    tituloUIPt:    'Limites Históricos do Rincón de Maneco, Uruguai 1934 (Área)',
    abstract:      '',
    geomType:      'polygon',
    labelField:    'nam',
    clipStrategy:  'none',
    special:       'historico',
    visible:       false,
    keywords:      ['límite histórico', '1934', 'rincón de maneco', 'historia uruguay', 'artigas', 'canelones', 'cerro largo', 'colonia', 'flores', 'florida', 'lavalleja', 'maldonado', 'montevideo', 'paysandú', 'rivera', 'río negro', 'salto', 'san josé', 'soriano', 'tacuarembó', 'treinta y tres'],
    keywordsEs:    ['límite histórico', '1934', 'rincón de maneco', 'historia uruguay', 'artigas'],
    keywordsEn:    ['historical boundary', 'uruguay history', '1934', 'rincón de maneco'],
    keywordsPt:    ['limite histórico', 'história uruguai', '1934', 'rincón de maneco'],
    attributes:    [
      { campo: 'objectid_1', labelEn: '', label: '', tipo: 'int', visible: false },
      { campo: 'departamen', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'acc', labelEn: 'Horizontal Accuracy Category', label: 'Categoría de precisión horizontal', tipo: 'short', visible: false },
      { campo: 'bst', labelEn: 'Boundary Status', label: 'Estado del límite', tipo: 'short', visible: false },
      { campo: 'nm3', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'nm4', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'nam', labelEn: 'Name', label: 'Nombre', tipo: 'string', visible: true },
      { campo: 'use_', labelEn: '', label: '', tipo: 'short', visible: false },
      { campo: 'localidad', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'escala', labelEn: '', label: '', tipo: 'short', visible: false },
      { campo: 'txt', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'hoja', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'sde_state_id', labelEn: '', label: '', tipo: 'long', visible: false },
    ],
  },

  limite_hist_1934_linea_uy: {
    source:        'igm_uy',
    srs:           'EPSG:4326',
    idioma:        'es',
    typename:      'Limites_Administrativos_Historicos_L:Limite_RinconDeManeco_10Ago1934',
    featureCount:  20,
    titulo:        'Limite RinconDeManeco - 10 Agosto 1934',
    tituloEs:      'Limite RinconDeManeco - 10 Agosto 1934',
    tituloEn:      'Historical Boundary',
    tituloPt:      'Limite Histórico',
    tituloUI:      'Límites históricos Rincón de Maneco 1934 (línea)',
    tituloUIEs:    'Límites históricos Rincón de Maneco 1934 (línea)',
    tituloUIEn:    'Historical Boundary of Rincón de Maneco 1934 of Uruguay',
    tituloUIPt:    'Limite Histórico do Rincón de Maneco 1934 do Uruguai',
    abstract:      '',
    geomType:      'line',
    labelField:    'def',
    clipStrategy:  'none',
    special:       'historico',
    visible:       false,
    keywords:      ['límite histórico', '1934', 'rincón de maneco', 'historia uruguay', 'artigas', 'canelones', 'cerro largo', 'colonia', 'durazno', 'flores', 'florida', 'lavalleja', 'maldonado', 'montevideo', 'paysandú', 'rincón de artigas  (constestado)', 'rivera', 'rocha', 'río negro', 'salto', 'san josé', 'soriano', 'tacuarembó', 'treinta y tres'],
    keywordsEs:    ['límite histórico', '1934', 'rincón de maneco', 'historia uruguay', 'artigas'],
    keywordsEn:    ['historical border', 'uruguay history', 'rincón de maneco', '1934'],
    keywordsPt:    ['fronteira histórica', 'história uruguai', 'rincón de maneco', '1934'],
    attributes:    [
      { campo: 'def', labelEn: '', label: '', tipo: 'string', visible: true },
      { campo: 'obs', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'fcode', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'use_', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'acc', labelEn: 'Horizontal Accuracy Category', label: 'Categoría de precisión horizontal', tipo: 'short', visible: false },
      { campo: 'bst', labelEn: 'Boundary Status', label: 'Estado del límite', tipo: 'short', visible: false },
      { campo: 'mn3', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'mn4', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'txt', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'depto', labelEn: '', label: '', tipo: 'string', visible: false },
      { campo: 'loc', labelEn: 'Vertical Relative Location', label: 'Posición vertical relativa', tipo: 'string', visible: false },
      { campo: 'escala', labelEn: '', label: '', tipo: 'short', visible: false },
      { campo: 'hoja', labelEn: '', label: '', tipo: 'decimal', visible: false },
      { campo: 'sde_state_id', labelEn: '', label: '', tipo: 'long', visible: false },
    ],
  },

};
