export const PNME_AR = {

  establecimiento_educativo_ar: {
    source:        'pnme_ar',
    srs:           'EPSG:4326',
    typename:      'publico:establecimiento_educativo',
    featureCount:   64639,
    titulo:        'establecimiento_educativo',
    tituloUI:      'Establecimientos educativos de Argentina',
    abstract:      'Establecimientos y su oferta educativa activa. Fuente: Padrón de establecimientos educativos. DIEE – Dirección Nacional de Evaluación e Información Educativa. Secretaría de Evaluación e Información Educativa. Ministerio de Educación de la Nación.',
    geomType:      'point',
    labelField:    'fna',
    clipStrategy:  'spatial',
    mask:          false,
    special:       false,
    visible:       true,
    keywords: [
      'establecimiento educativo', 'establecimientos educativos',
      'escuela', 'escuelas', 'colegio', 'colegios',
      'instituto', 'institutos', 'jardín', 'jardines', 'jardin',
      'educación', 'educacion', 'nivel educativo',
      'escuela primaria', 'escuela secundaria', 'escuela técnica', 'escuela tecnica',
      'escuela pública', 'escuela publica', 'escuela privada',
      'gestión pública', 'gestión privada', 'gestion publica', 'gestion privada',
      'modalidad educativa', 'oferta educativa',
      'ámbito urbano', 'ámbito rural', 'ambito urbano', 'ambito rural',
      'mapa educativo', 'padrón educativo', 'padron educativo',
    ],
    attributes: [
      { campo: 'gid',                       labelEn: '',             label: '',                        tipo: 'decimal', visible: false },
      { campo: 'fna',                        labelEn: 'Full name',    label: 'Nombre completo',         tipo: 'string',  visible: true  },
      { campo: 'gna',                        labelEn: 'Generic name', label: 'Tipo de establecimiento', tipo: 'string',  visible: true  },
      { campo: 'nam',                        labelEn: 'Name',         label: 'Nombre',                  tipo: 'string',  visible: true  },
      { campo: 'fun',                        labelEn: 'Status',       label: 'Estado',                  tipo: 'string',  visible: true  },
      { campo: 'cue',                        labelEn: 'CUE code',     label: 'Código CUE',              tipo: 'string',  visible: false },
      { campo: 'amg',                        labelEn: 'Area type',    label: 'Ámbito',                  tipo: 'string',  visible: true  },
      { campo: 'ges',                        labelEn: 'Management',   label: 'Gestión',                 tipo: 'string',  visible: true  },
      { campo: 'mde',                        labelEn: 'Modality',     label: 'Modalidad',               tipo: 'string',  visible: true  },
      { campo: 'nen',                        labelEn: 'Level',        label: 'Nivel educativo',         tipo: 'string',  visible: true  },
      { campo: 'sag',                        labelEn: '',             label: '',                        tipo: 'string',  visible: false },
      { campo: 'pre',                        labelEn: '',             label: '',                        tipo: 'string',  visible: false },
      { campo: 'establecimiento_educativo',  labelEn: '',             label: '',                        tipo: 'string',  visible: false },
    ],
  },

  ministerio_educacion_ar: {
    source:        'pnme_ar',
    srs:           'EPSG:4326',
    typename:      'publico:ministerios_educacion',
    featureCount:   25,
    titulo:        'ministerios_educacion',
    tituloUI:      'Ministerios de Educación de Argentina',
    abstract:      'Ministerios y organismos provinciales de Educación de la República Argentina. Un punto por provincia más la Nación.',
    geomType:      'point',
    labelField:    'nombre',
    clipStrategy:  'attribute',
    clipField:     'provincia',
    mask:          false,
    special:       false,
    visible:       true,
    keywords: [
      'ministerio de educación', 'ministerio de educacion',
      'ministerios de educación', 'ministerios de educacion',
      'organismo educativo', 'organismos educativos',
      'autoridad educativa', 'autoridades educativas',
      'dirección general de educación', 'direccion general de educacion',
      'consejo de educación', 'consejo de educacion',
      'sede ministerio', 'sede educación', 'sede educacion',
    ],
    attributes: [
      { campo: 'cod_prov',               labelEn: '',           label: '',          tipo: 'string', visible: false },
      { campo: 'pais',                   labelEn: '',           label: '',          tipo: 'string', visible: false },
      { campo: 'provincia',              labelEn: 'Province',   label: 'Provincia', tipo: 'string', visible: true  },
      { campo: 'localidad',              labelEn: 'City',       label: 'Localidad', tipo: 'string', visible: true  },
      { campo: 'direccion',              labelEn: 'Address',    label: 'Dirección', tipo: 'string', visible: true  },
      { campo: 'telefono',               labelEn: 'Phone',      label: 'Teléfono',  tipo: 'string', visible: true  },
      { campo: 'nombre',                 labelEn: 'Name',       label: 'Nombre',    tipo: 'string', visible: true  },
      { campo: 'ministerios_educacion',  labelEn: '',           label: '',          tipo: 'string', visible: false },
    ],
  },

};
