export const SE_AR = {

  establecimiento_educativo_ar: {
    source:        'se_ar',
    srs:           'EPSG:4326',
    idioma:     'es',
    typename:      'publico:establecimiento_educativo',
    featureCount:   64639,
    titulo:        'establecimiento_educativo',
    tituloEs:   'establecimiento_educativo',
    tituloEn:   'School',
    tituloPt:   'Escola',
    tituloUI:      'Establecimientos educativos de Argentina',
    tituloUIEs: 'Establecimientos educativos de Argentina',
    tituloUIEn: 'Educational Establishments of Argentina',
    tituloUIPt: 'Estabelecimentos Educacionais da Argentina',
    abstract:      'Establecimientos y su oferta educativa activa. Fuente: Padrón de establecimientos educativos. DIEE – Dirección Nacional de Evaluación e Información Educativa. Secretaría de Evaluación e Información Educativa. Ministerio de Educación de la Nación.',
    geomType:      'point',
    labelField:    'fna',
    clipStrategy:  'spatial',
    mask:          false,
    special:       false,
    visible:       true,
    keywords: [
      'establecimiento educativo', 'establecimientos educativos',
      'escuela', 'escuelas', 'colegio', 'colegios',
      'instituto', 'institutos', 'jardín', 'jardines', 'jardin',
      'educación', 'educacion', 'nivel educativo',
      'escuela primaria', 'escuela secundaria', 'escuela técnica', 'escuela tecnica',
      'escuela pública', 'escuela publica', 'escuela privada',
      'gestión pública', 'gestión privada', 'gestion publica', 'gestion privada',
      'modalidad educativa', 'oferta educativa',
      'ámbito urbano', 'ámbito rural', 'ambito urbano', 'ambito rural',
      'mapa educativo', 'padrón educativo', 'padron educativo',
    ],
    keywordsEs: ['establecimiento educativo', 'establecimientos educativos', 'escuela', 'escuelas', 'colegio'],
    keywordsEn: ['school', 'education', 'university'],
    keywordsPt: ['escola', 'educação', 'universidade'],
    attributes: [
      { campo: 'gid',                       labelEn: '',             label: '',                        tipo: 'decimal', visible: false },
      { campo: 'fna',                        labelEn: 'Full name',    label: 'Nombre completo',         tipo: 'string',  visible: true  },
      { campo: 'gna',                        labelEn: 'Generic name', label: 'Tipo de establecimiento', tipo: 'string',  visible: true  },
      { campo: 'nam',                        labelEn: 'Name',         label: 'Nombre',                  tipo: 'string',  visible: true  },
      { campo: 'fun',                        labelEn: 'Status',       label: 'Estado',                  tipo: 'string',  visible: true  },
      { campo: 'cue',                        labelEn: 'CUE code',     label: 'Código CUE',              tipo: 'string',  visible: false },
      { campo: 'amg',                        labelEn: 'Area type',    label: 'Ámbito',                  tipo: 'string',  visible: true  },
      { campo: 'ges',                        labelEn: 'Management',   label: 'Gestión',                 tipo: 'string',  visible: true  },
      { campo: 'mde',                        labelEn: 'Modality',     label: 'Modalidad',               tipo: 'string',  visible: true  },
      { campo: 'nen',                        labelEn: 'Level',        label: 'Nivel educativo',         tipo: 'string',  visible: true  },
      { campo: 'sag',                        labelEn: '',             label: '',                        tipo: 'string',  visible: false },
      { campo: 'pre',                        labelEn: '',             label: '',                        tipo: 'string',  visible: false },
      { campo: 'establecimiento_educativo',  labelEn: '',             label: '',                        tipo: 'string',  visible: false },
    ],
  },

  institucion_universitaria_ar: {
    source:        'se_ar',
    srs:           'EPSG:4326',
    idioma:     'es',
    typename:      'publico:institucion_universitaria',
    featureCount:   1447,
    titulo:        'institucion_universitaria',
    tituloEs:   'institucion_universitaria',
    tituloEn:   'University',
    tituloPt:   'Universidade',
    tituloUI:      'Instituciones universitarias de Argentina',
    tituloUIEs: 'Instituciones universitarias de Argentina',
    tituloUIEn: 'University Institutions of Argentina',
    tituloUIPt: 'Instituições Universitárias da Argentina',
    abstract:      'Elaboración propia en base a listado SPU de universidades y unidades académicas 2023.',
    geomType:      'point',
    labelField:    'universidad',
    clipStrategy:  'attribute',
    clipField:     'provincia',
    mask:          false,
    special:       false,
    visible:       true,
    keywords: [
      'universidad', 'universidades', 'universitario', 'universitaria',
      'facultad', 'facultades', 'unidad académica', 'unidades académicas', 'unidad academica',
      'educación superior', 'educacion superior', 'nivel superior',
      'instituto universitario', 'institutos universitarios',
      'sede universitaria', 'sedes universitarias',
      'estatal', 'privado', 'régimen universitario',
      'SPU', 'CUE',
    ],
    keywordsEs: ['universidad', 'universidades', 'universitario', 'universitaria', 'facultad'],
    keywordsEn: ['university', 'college', 'campus', 'school', 'education'],
    keywordsPt: ['universidade', 'faculdade', 'campus', 'escola', 'educação'],
    attributes: [
      { campo: 'regimen',                  labelEn: 'Regime',           label: 'Régimen',           tipo: 'string',  visible: true  },
      { campo: 'id_universidad',           labelEn: '',                 label: '',                  tipo: 'int',     visible: false },
      { campo: 'universidad',              labelEn: 'University',       label: 'Universidad',       tipo: 'string',  visible: true  },
      { campo: 'id_ua',                    labelEn: '',                 label: '',                  tipo: 'int',     visible: false },
      { campo: 'unidad_academica',         labelEn: 'Academic unit',    label: 'Unidad académica',  tipo: 'string',  visible: true  },
      { campo: 'cue',                      labelEn: 'CUE code',         label: 'Código CUE',        tipo: 'string',  visible: false },
      { campo: 'niveles',                  labelEn: 'Levels',           label: 'Niveles',           tipo: 'string',  visible: true  },
      { campo: 'domicilio',                labelEn: 'Address',          label: 'Domicilio',         tipo: 'string',  visible: true  },
      { campo: 'codigo_postal',            labelEn: 'Postal code',      label: 'Código postal',     tipo: 'string',  visible: false },
      { campo: 'localidad',                labelEn: 'City',             label: 'Localidad',         tipo: 'string',  visible: true  },
      { campo: 'provincia',                labelEn: 'Province',         label: 'Provincia',         tipo: 'string',  visible: true  },
      { campo: 'latitud',                  labelEn: '',                 label: '',                  tipo: 'decimal', visible: false },
      { campo: 'longitud',                 labelEn: '',                 label: '',                  tipo: 'decimal', visible: false },
      { campo: 'web',                      labelEn: 'Website',          label: 'Sitio web',         tipo: 'string',  visible: true  },
      { campo: 'institucion_universitaria',labelEn: '',                 label: '',                  tipo: 'string',  visible: false },
    ],
  },

  ministerio_educacion_ar: {
    source:        'se_ar',
    srs:           'EPSG:4326',
    idioma:     'es',
    typename:      'publico:ministerios_educacion',
    featureCount:   25,
    titulo:        'ministerios_educacion',
    tituloEs:   'ministerios_educacion',
    tituloEn:   'Ministry of Education',
    tituloPt:   'Ministério de Educação',
    tituloUI:      'Ministerios de Educación de Argentina',
    tituloUIEs: 'Ministerios de Educación de Argentina',
    tituloUIEn: 'Ministries of Education of Argentina',
    tituloUIPt: 'Ministérios de Educação da Argentina',
    abstract:      'Ministerios y organismos provinciales de Educación de la República Argentina. Un punto por provincia más la Nación.',
    geomType:      'point',
    labelField:    'nombre',
    clipStrategy:  'attribute',
    clipField:     'provincia',
    mask:          false,
    special:       false,
    visible:       true,
    keywords: [
      'ministerio de educación', 'ministerio de educacion',
      'ministerios de educación', 'ministerios de educacion',
      'organismo educativo', 'organismos educativos',
      'autoridad educativa', 'autoridades educativas',
      'dirección general de educación', 'direccion general de educacion',
      'consejo de educación', 'consejo de educacion',
      'sede ministerio', 'sede educación', 'sede educacion',
    ],
    keywordsEs: ['ministerio de educación', 'ministerio de educacion', 'ministerios de educación', 'ministerios de educacion', 'organismo educativo'],
    keywordsEn: ['ministry of education', 'education department', 'school administration'],
    keywordsPt: ['ministério de educação', 'departamento de educação', 'administração escolar'],
    attributes: [
      { campo: 'cod_prov',               labelEn: '',           label: '',          tipo: 'string', visible: false },
      { campo: 'pais',                   labelEn: '',           label: '',          tipo: 'string', visible: false },
      { campo: 'provincia',              labelEn: 'Province',   label: 'Provincia', tipo: 'string', visible: true  },
      { campo: 'localidad',              labelEn: 'City',       label: 'Localidad', tipo: 'string', visible: true  },
      { campo: 'direccion',              labelEn: 'Address',    label: 'Dirección', tipo: 'string', visible: true  },
      { campo: 'telefono',               labelEn: 'Phone',      label: 'Teléfono',  tipo: 'string', visible: true  },
      { campo: 'nombre',                 labelEn: 'Name',       label: 'Nombre',    tipo: 'string', visible: true  },
      { campo: 'ministerios_educacion',  labelEn: '',           label: '',          tipo: 'string', visible: false },
    ],
  },

};
