/**
 * DEPARTAMENTOS_MAP_AR
 *
 * Generado desde el WFS de IGN Argentina (529 departamentos/partidos).
 * Estructura:
 *   - Entrada única   → { provincia, value }         (sin ambigüedad, 400 entradas)
 *   - Entrada ambigua → [{ provincia, value }, ...]  (requiere desambiguación, 47 entradas)
 *
 * Usado por GEO_MAPS en layers/index.js.
 */
export const DEPARTAMENTOS_MAP_AR = {

  // ── Únicos (384) ─────────────────────────────────────────────────

  '12 de octubre': { provincia: 'Chaco', value: '12 de Octubre' },
  '2 de abril': { provincia: 'Chaco', value: '2 de Abril' },
  'adolfo gonzales chaves': { provincia: 'Buenos Aires', value: 'Adolfo Gonzales Chaves' },
  'aguirre': { provincia: 'Santiago del Estero', value: 'Aguirre' },
  'albardon': { provincia: 'San Juan', value: 'Albardón' },
  'alberdi': { provincia: 'Santiago del Estero', value: 'Alberdi' },
  'alberti': { provincia: 'Buenos Aires', value: 'Alberti' },
  'alumine': { provincia: 'Neuquén', value: 'Aluminé' },
  'ambato': { provincia: 'Catamarca', value: 'Ambato' },
  'ancasti': { provincia: 'Catamarca', value: 'Ancasti' },
  'andalgala': { provincia: 'Catamarca', value: 'Andalgalá' },
  'anelo': { provincia: 'Neuquén', value: 'Añelo' },
  'angaco': { provincia: 'San Juan', value: 'Angaco' },
  'angel vicente penaloza': { provincia: 'La Rioja', value: 'Ángel Vicente Peñaloza' },
  'anta': { provincia: 'Salta', value: 'Anta' },
  'antartida argentina': { provincia: 'Tierra del Fuego, Antártida e Islas del Atlántico Sur', value: 'Antártida Argentina' },
  'antofagasta de la sierra': { provincia: 'Catamarca', value: 'Antofagasta de la Sierra' },
  'apostoles': { provincia: 'Misiones', value: 'Apóstoles' },
  'arauco': { provincia: 'La Rioja', value: 'Arauco' },
  'arrecifes': { provincia: 'Buenos Aires', value: 'Arrecifes' },
  'atamisqui': { provincia: 'Santiago del Estero', value: 'Atamisqui' },
  'atreuco': { provincia: 'La Pampa', value: 'Atreucó' },
  'azul': { provincia: 'Buenos Aires', value: 'Azul' },
  'bahia blanca': { provincia: 'Buenos Aires', value: 'Bahía Blanca' },
  'balcarce': { provincia: 'Buenos Aires', value: 'Balcarce' },
  'banda': { provincia: 'Santiago del Estero', value: 'Banda' },
  'baradero': { provincia: 'Buenos Aires', value: 'Baradero' },
  'bariloche': { provincia: 'Río Negro', value: 'Bariloche' },
  'belen': { provincia: 'Catamarca', value: 'Belén' },
  'bella vista': { provincia: 'Corrientes', value: 'Bella Vista' },
  'benito juarez': { provincia: 'Buenos Aires', value: 'Benito Juárez' },
  'berazategui': { provincia: 'Buenos Aires', value: 'Berazategui' },
  'berisso': { provincia: 'Buenos Aires', value: 'Berisso' },
  'beron de astrada': { provincia: 'Corrientes', value: 'Berón de Astrada' },
  'biedma': { provincia: 'Chubut', value: 'Biedma' },
  'bolivar': { provincia: 'Buenos Aires', value: 'Bolívar' },
  'bragado': { provincia: 'Buenos Aires', value: 'Bragado' },
  'brandsen': { provincia: 'Buenos Aires', value: 'Brandsen' },
  'burruyacu': { provincia: 'Tucumán', value: 'Burruyacú' },
  'cachi': { provincia: 'Salta', value: 'Cachi' },
  'cafayate': { provincia: 'Salta', value: 'Cafayate' },
  'cainguas': { provincia: 'Misiones', value: 'Cainguás' },
  'calamuchita': { provincia: 'Córdoba', value: 'Calamuchita' },
  'caleu caleu': { provincia: 'La Pampa', value: 'Caleu Caleu' },
  'calingasta': { provincia: 'San Juan', value: 'Calingasta' },
  'campana': { provincia: 'Buenos Aires', value: 'Campana' },
  'candelaria': { provincia: 'Misiones', value: 'Candelaria' },
  'canuelas': { provincia: 'Buenos Aires', value: 'Cañuelas' },
  'capayan': { provincia: 'Catamarca', value: 'Capayán' },
  'capitan sarmiento': { provincia: 'Buenos Aires', value: 'Capitán Sarmiento' },
  'carlos casares': { provincia: 'Buenos Aires', value: 'Carlos Casares' },
  'carlos tejedor': { provincia: 'Buenos Aires', value: 'Carlos Tejedor' },
  'carmen de areco': { provincia: 'Buenos Aires', value: 'Carmen de Areco' },
  'caseros': { provincia: 'Santa Fe', value: 'Caseros' },
  'castellanos': { provincia: 'Santa Fe', value: 'Castellanos' },
  'castelli': { provincia: 'Buenos Aires', value: 'Castelli' },
  'castro barros': { provincia: 'La Rioja', value: 'Castro Barros' },
  'catan lil': { provincia: 'Neuquén', value: 'Catán Lil' },
  'catrilo': { provincia: 'La Pampa', value: 'Catriló' },
  'caucete': { provincia: 'San Juan', value: 'Caucete' },
  'cerrillos': { provincia: 'Salta', value: 'Cerrillos' },
  'chalileo': { provincia: 'La Pampa', value: 'Chalileo' },
  'chamical': { provincia: 'La Rioja', value: 'Chamical' },
  'chapaleufu': { provincia: 'La Pampa', value: 'Chapaleufú' },
  'chascomus': { provincia: 'Buenos Aires', value: 'Chascomús' },
  'chical co': { provincia: 'La Pampa', value: 'Chical Co' },
  'chicligasta': { provincia: 'Tucumán', value: 'Chicligasta' },
  'chicoana': { provincia: 'Salta', value: 'Chicoana' },
  'chilecito': { provincia: 'La Rioja', value: 'Chilecito' },
  'chimbas': { provincia: 'San Juan', value: 'Chimbas' },
  'chivilcoy': { provincia: 'Buenos Aires', value: 'Chivilcoy' },
  'chos malal': { provincia: 'Neuquén', value: 'Chos Malal' },
  'choya': { provincia: 'Santiago del Estero', value: 'Choya' },
  'cochinoca': { provincia: 'Jujuy', value: 'Cochinoca' },
  'collon cura': { provincia: 'Neuquén', value: 'Collón Curá' },
  'comandante fernandez': { provincia: 'Chaco', value: 'Comandante Fernández' },
  'concordia': { provincia: 'Entre Ríos', value: 'Concordia' },
  'conesa': { provincia: 'Río Negro', value: 'Conesa' },
  'confluencia': { provincia: 'Neuquén', value: 'Confluencia' },
  'conhelo': { provincia: 'La Pampa', value: 'Conhelo' },
  'constitucion': { provincia: 'Santa Fe', value: 'Constitución' },
  'copo': { provincia: 'Santiago del Estero', value: 'Copo' },
  'coronel de marina leonardo rosales': { provincia: 'Buenos Aires', value: 'Coronel de Marina Leonardo Rosales' },
  'coronel dorrego': { provincia: 'Buenos Aires', value: 'Coronel Dorrego' },
  'coronel suarez': { provincia: 'Buenos Aires', value: 'Coronel Suárez' },
  'corpen aike': { provincia: 'Santa Cruz', value: 'Corpen Aike' },
  'cruz alta': { provincia: 'Tucumán', value: 'Cruz Alta' },
  'cruz del eje': { provincia: 'Córdoba', value: 'Cruz del Eje' },
  'curaco': { provincia: 'La Pampa', value: 'Curacó' },
  'curuzu cuatia': { provincia: 'Corrientes', value: 'Curuzú Cuatiá' },
  'cushamen': { provincia: 'Chubut', value: 'Cushamen' },
  'daireaux': { provincia: 'Buenos Aires', value: 'Daireaux' },
  'deseado': { provincia: 'Santa Cruz', value: 'Deseado' },
  'diamante': { provincia: 'Entre Ríos', value: 'Diamante' },
  'dolores': { provincia: 'Buenos Aires', value: 'Dolores' },
  'dr. manuel belgrano': { provincia: 'Jujuy', value: 'Dr. Manuel Belgrano' },
  'el alto': { provincia: 'Catamarca', value: 'El Alto' },
  'el carmen': { provincia: 'Jujuy', value: 'El Carmen' },
  'el cuy': { provincia: 'Río Negro', value: 'El Cuy' },
  'eldorado': { provincia: 'Misiones', value: 'Eldorado' },
  'empedrado': { provincia: 'Corrientes', value: 'Empedrado' },
  'ensenada': { provincia: 'Buenos Aires', value: 'Ensenada' },
  'escalante': { provincia: 'Chubut', value: 'Escalante' },
  'escobar': { provincia: 'Buenos Aires', value: 'Escobar' },
  'esquina': { provincia: 'Corrientes', value: 'Esquina' },
  'esteban echeverria': { provincia: 'Buenos Aires', value: 'Esteban Echeverría' },
  'exaltacion de la cruz': { provincia: 'Buenos Aires', value: 'Exaltación de la Cruz' },
  'ezeiza': { provincia: 'Buenos Aires', value: 'Ezeiza' },
  'famailla': { provincia: 'Tucumán', value: 'Famaillá' },
  'famatina': { provincia: 'La Rioja', value: 'Famatina' },
  'federacion': { provincia: 'Entre Ríos', value: 'Federación' },
  'federal': { provincia: 'Entre Ríos', value: 'Federal' },
  'feliciano': { provincia: 'Entre Ríos', value: 'Feliciano' },
  'figueroa': { provincia: 'Santiago del Estero', value: 'Figueroa' },
  'florencio varela': { provincia: 'Buenos Aires', value: 'Florencio Varela' },
  'formosa': { provincia: 'Formosa', value: 'Formosa' },
  'fray justo santa maria de oro': { provincia: 'Chaco', value: 'Fray Justo Santa María de Oro' },
  'fray mamerto esquiu': { provincia: 'Catamarca', value: 'Fray Mamerto Esquiú' },
  'futaleufu': { provincia: 'Chubut', value: 'Futaleufú' },
  'gaiman': { provincia: 'Chubut', value: 'Gaiman' },
  'garay': { provincia: 'Santa Fe', value: 'Garay' },
  'gastre': { provincia: 'Chubut', value: 'Gastre' },
  'general alvarado': { provincia: 'Buenos Aires', value: 'General Alvarado' },
  'general arenales': { provincia: 'Buenos Aires', value: 'General Arenales' },
  'general donovan': { provincia: 'Chaco', value: 'General Donovan' },
  'general felipe varela': { provincia: 'La Rioja', value: 'General Felipe Varela' },
  'general guido': { provincia: 'Buenos Aires', value: 'General Guido' },
  'general jose de san martin': { provincia: 'Salta', value: 'General José de San Martín' },
  'general juan facundo quiroga': { provincia: 'La Rioja', value: 'General Juan Facundo Quiroga' },
  'general juan madariaga': { provincia: 'Buenos Aires', value: 'General Juan Madariaga' },
  'general la madrid': { provincia: 'Buenos Aires', value: 'General La Madrid' },
  'general lamadrid': { provincia: 'La Rioja', value: 'General Lamadrid' },
  'general las heras': { provincia: 'Buenos Aires', value: 'General Las Heras' },
  'general lavalle': { provincia: 'Buenos Aires', value: 'General Lavalle' },
  'general lopez': { provincia: 'Santa Fe', value: 'General López' },
  'general manuel belgrano': { provincia: 'Misiones', value: 'General Manuel Belgrano' },
  'general obligado': { provincia: 'Santa Fe', value: 'General Obligado' },
  'general ortiz de ocampo': { provincia: 'La Rioja', value: 'General Ortiz de Ocampo' },
  'general pedernera': { provincia: 'San Luis', value: 'General Pedernera' },
  'general pinto': { provincia: 'Buenos Aires', value: 'General Pinto' },
  'general pueyrredon': { provincia: 'Buenos Aires', value: 'General Pueyrredón' },
  'general rodriguez': { provincia: 'Buenos Aires', value: 'General Rodríguez' },
  'general taboada': { provincia: 'Santiago del Estero', value: 'General Taboada' },
  'general viamonte': { provincia: 'Buenos Aires', value: 'General Viamonte' },
  'general villegas': { provincia: 'Buenos Aires', value: 'General Villegas' },
  'gobernador dupuy': { provincia: 'San Luis', value: 'Gobernador Dupuy' },
  'godoy cruz': { provincia: 'Mendoza', value: 'Godoy Cruz' },
  'goya': { provincia: 'Corrientes', value: 'Goya' },
  'graneros': { provincia: 'Tucumán', value: 'Graneros' },
  'guachipas': { provincia: 'Salta', value: 'Guachipas' },
  'gualeguay': { provincia: 'Entre Ríos', value: 'Gualeguay' },
  'gualeguaychu': { provincia: 'Entre Ríos', value: 'Gualeguaychú' },
  'guamini': { provincia: 'Buenos Aires', value: 'Guaminí' },
  'guarani': { provincia: 'Misiones', value: 'Guaraní' },
  'guasayan': { provincia: 'Santiago del Estero', value: 'Guasayán' },
  'guatrache': { provincia: 'La Pampa', value: 'Guatraché' },
  'guaymallen': { provincia: 'Mendoza', value: 'Guaymallén' },
  'guer aike': { provincia: 'Santa Cruz', value: 'Güer Aike' },
  'hipolito yrigoyen': { provincia: 'Buenos Aires', value: 'Hipólito Yrigoyen' },
  'hucal': { provincia: 'La Pampa', value: 'Hucal' },
  'huiliches': { provincia: 'Neuquén', value: 'Huiliches' },
  'humahuaca': { provincia: 'Jujuy', value: 'Humahuaca' },
  'hurlingham': { provincia: 'Buenos Aires', value: 'Hurlingham' },
  'iglesia': { provincia: 'San Juan', value: 'Iglesia' },
  'iguazu': { provincia: 'Misiones', value: 'Iguazú' },
  'iriondo': { provincia: 'Santa Fe', value: 'Iriondo' },
  'iruya': { provincia: 'Salta', value: 'Iruya' },
  'ischilin': { provincia: 'Córdoba', value: 'Ischilín' },
  'islas del atlantico sur': { provincia: 'Tierra del Fuego, Antártida e Islas del Atlántico Sur', value: 'Islas del Atlántico Sur' },
  'islas del ibicuy': { provincia: 'Entre Ríos', value: 'Islas del Ibicuy' },
  'itati': { provincia: 'Corrientes', value: 'Itatí' },
  'jachal': { provincia: 'San Juan', value: 'Jáchal' },
  'jimenez': { provincia: 'Santiago del Estero', value: 'Jiménez' },
  'jose c. paz': { provincia: 'Buenos Aires', value: 'José C. Paz' },
  'juan bautista alberdi': { provincia: 'Tucumán', value: 'Juan Bautista Alberdi' },
  'juan felipe ibarra': { provincia: 'Santiago del Estero', value: 'Juan Felipe Ibarra' },
  'juan martin de pueyrredon': { provincia: 'San Luis', value: 'Juan Martín de Pueyrredón' },
  'juarez celman': { provincia: 'Córdoba', value: 'Juárez Celman' },
  'la caldera': { provincia: 'Salta', value: 'La Caldera' },
  'la candelaria': { provincia: 'Salta', value: 'La Candelaria' },
  'la capital': { provincia: 'Santa Fe', value: 'La Capital' },
  'la cocha': { provincia: 'Tucumán', value: 'La Cocha' },
  'la costa': { provincia: 'Buenos Aires', value: 'La Costa' },
  'la matanza': { provincia: 'Buenos Aires', value: 'La Matanza' },
  'la plata': { provincia: 'Buenos Aires', value: 'La Plata' },
  'la poma': { provincia: 'Salta', value: 'La Poma' },
  'la vina': { provincia: 'Salta', value: 'La Viña' },
  'lacar': { provincia: 'Neuquén', value: 'Lácar' },
  'lago argentino': { provincia: 'Santa Cruz', value: 'Lago Argentino' },
  'lago buenos aires': { provincia: 'Santa Cruz', value: 'Lago Buenos Aires' },
  'laishi': { provincia: 'Formosa', value: 'Laishi' },
  'languineo': { provincia: 'Chubut', value: 'Languiñeo' },
  'lanus': { provincia: 'Buenos Aires', value: 'Lanús' },
  'laprida': { provincia: 'Buenos Aires', value: 'Laprida' },
  'las colonias': { provincia: 'Santa Fe', value: 'Las Colonias' },
  'las flores': { provincia: 'Buenos Aires', value: 'Las Flores' },
  'las heras': { provincia: 'Mendoza', value: 'Las Heras' },
  'leales': { provincia: 'Tucumán', value: 'Leales' },
  'ledesma': { provincia: 'Jujuy', value: 'Ledesma' },
  'lezama': { provincia: 'Buenos Aires', value: 'Lezama' },
  'libertad': { provincia: 'Chaco', value: 'Libertad' },
  'lihuel calel': { provincia: 'La Pampa', value: 'Lihuel Calel' },
  'limay mahuida': { provincia: 'La Pampa', value: 'Limay Mahuida' },
  'lincoln': { provincia: 'Buenos Aires', value: 'Lincoln' },
  'loberia': { provincia: 'Buenos Aires', value: 'Lobería' },
  'lobos': { provincia: 'Buenos Aires', value: 'Lobos' },
  'lomas de zamora': { provincia: 'Buenos Aires', value: 'Lomas de Zamora' },
  'loncopue': { provincia: 'Neuquén', value: 'Loncopué' },
  'loreto': { provincia: 'Santiago del Estero', value: 'Loreto' },
  'los andes': { provincia: 'Salta', value: 'Los Andes' },
  'los lagos': { provincia: 'Neuquén', value: 'Los Lagos' },
  'loventue': { provincia: 'La Pampa', value: 'Loventué' },
  'lujan': { provincia: 'Buenos Aires', value: 'Luján' },
  'lujan de cuyo': { provincia: 'Mendoza', value: 'Luján de Cuyo' },
  'lules': { provincia: 'Tucumán', value: 'Lules' },
  'magallanes': { provincia: 'Santa Cruz', value: 'Magallanes' },
  'magdalena': { provincia: 'Buenos Aires', value: 'Magdalena' },
  'malargue': { provincia: 'Mendoza', value: 'Malargüe' },
  'malvinas argentinas': { provincia: 'Buenos Aires', value: 'Malvinas Argentinas' },
  'mar chiquita': { provincia: 'Buenos Aires', value: 'Mar Chiquita' },
  'maraco': { provincia: 'La Pampa', value: 'Maracó' },
  'marcos juarez': { provincia: 'Córdoba', value: 'Marcos Juárez' },
  'marcos paz': { provincia: 'Buenos Aires', value: 'Marcos Paz' },
  'martires': { provincia: 'Chubut', value: 'Mártires' },
  'matacos': { provincia: 'Formosa', value: 'Matacos' },
  'mayor luis j. fontana': { provincia: 'Chaco', value: 'Mayor Luis J. Fontana' },
  'mburucuya': { provincia: 'Corrientes', value: 'Mburucuyá' },
  'merlo': { provincia: 'Buenos Aires', value: 'Merlo' },
  'metan': { provincia: 'Salta', value: 'Metán' },
  'mitre': { provincia: 'Santiago del Estero', value: 'Mitre' },
  'molinos': { provincia: 'Salta', value: 'Molinos' },
  'monte': { provincia: 'Buenos Aires', value: 'Monte' },
  'monte caseros': { provincia: 'Corrientes', value: 'Monte Caseros' },
  'monte hermoso': { provincia: 'Buenos Aires', value: 'Monte Hermoso' },
  'montecarlo': { provincia: 'Misiones', value: 'Montecarlo' },
  'monteros': { provincia: 'Tucumán', value: 'Monteros' },
  'moron': { provincia: 'Buenos Aires', value: 'Morón' },
  'navarro': { provincia: 'Buenos Aires', value: 'Navarro' },
  'necochea': { provincia: 'Buenos Aires', value: 'Necochea' },
  'nogoya': { provincia: 'Entre Ríos', value: 'Nogoyá' },
  'norquin': { provincia: 'Neuquén', value: 'Ñorquín' },
  'norquinco': { provincia: 'Río Negro', value: 'Ñorquinco' },
  'o\'higgins': { provincia: 'Chaco', value: 'O\'Higgins' },
  'obera': { provincia: 'Misiones', value: 'Oberá' },
  'ojo de agua': { provincia: 'Santiago del Estero', value: 'Ojo de Agua' },
  'olavarria': { provincia: 'Buenos Aires', value: 'Olavarría' },
  'oran': { provincia: 'Salta', value: 'Orán' },
  'paclin': { provincia: 'Catamarca', value: 'Paclín' },
  'palpala': { provincia: 'Jujuy', value: 'Palpalá' },
  'parana': { provincia: 'Entre Ríos', value: 'Paraná' },
  'paso de indios': { provincia: 'Chubut', value: 'Paso de Indios' },
  'paso de los libres': { provincia: 'Corrientes', value: 'Paso de los Libres' },
  'patagones': { provincia: 'Buenos Aires', value: 'Patagones' },
  'patino': { provincia: 'Formosa', value: 'Patiño' },
  'pehuajo': { provincia: 'Buenos Aires', value: 'Pehuajó' },
  'pehuenches': { provincia: 'Neuquén', value: 'Pehuenches' },
  'pergamino': { provincia: 'Buenos Aires', value: 'Pergamino' },
  'pichi mahuida': { provincia: 'Río Negro', value: 'Pichi Mahuida' },
  'picun leufu': { provincia: 'Neuquén', value: 'Picún Leufú' },
  'picunches': { provincia: 'Neuquén', value: 'Picunches' },
  'pila': { provincia: 'Buenos Aires', value: 'Pila' },
  'pilagas': { provincia: 'Formosa', value: 'Pilagás' },
  'pilar': { provincia: 'Buenos Aires', value: 'Pilar' },
  'pilcaniyeu': { provincia: 'Río Negro', value: 'Pilcaniyeu' },
  'pilcomayo': { provincia: 'Formosa', value: 'Pilcomayo' },
  'pinamar': { provincia: 'Buenos Aires', value: 'Pinamar' },
  'pirane': { provincia: 'Formosa', value: 'Pirané' },
  'pocho': { provincia: 'Córdoba', value: 'Pocho' },
  'pocito': { provincia: 'San Juan', value: 'Pocito' },
  'poman': { provincia: 'Catamarca', value: 'Pomán' },
  'presidencia de la plaza': { provincia: 'Chaco', value: 'Presidencia de la Plaza' },
  'presidente peron': { provincia: 'Buenos Aires', value: 'Presidente Perón' },
  'presidente roque saenz pena': { provincia: 'Córdoba', value: 'Presidente Roque Sáenz Peña' },
  'puan': { provincia: 'Buenos Aires', value: 'Puán' },
  'puelen': { provincia: 'La Pampa', value: 'Puelén' },
  'punilla': { provincia: 'Córdoba', value: 'Punilla' },
  'punta indio': { provincia: 'Buenos Aires', value: 'Punta Indio' },
  'quebrachos': { provincia: 'Santiago del Estero', value: 'Quebrachos' },
  'quemu quemu': { provincia: 'La Pampa', value: 'Quemú Quemú' },
  'quilmes': { provincia: 'Buenos Aires', value: 'Quilmes' },
  'quitilipi': { provincia: 'Chaco', value: 'Quitilipi' },
  'ramallo': { provincia: 'Buenos Aires', value: 'Ramallo' },
  'ramon lista': { provincia: 'Formosa', value: 'Ramón Lista' },
  'rancul': { provincia: 'La Pampa', value: 'Rancul' },
  'rauch': { provincia: 'Buenos Aires', value: 'Rauch' },
  'realico': { provincia: 'La Pampa', value: 'Realicó' },
  'rinconada': { provincia: 'Jujuy', value: 'Rinconada' },
  'rio cuarto': { provincia: 'Córdoba', value: 'Río Cuarto' },
  'rio grande': { provincia: 'Tierra del Fuego, Antártida e Islas del Atlántico Sur', value: 'Río Grande' },
  'rio hondo': { provincia: 'Santiago del Estero', value: 'Río Hondo' },
  'rio primero': { provincia: 'Córdoba', value: 'Río Primero' },
  'rio seco': { provincia: 'Córdoba', value: 'Río Seco' },
  'rio segundo': { provincia: 'Córdoba', value: 'Río Segundo' },
  'rio senguer': { provincia: 'Chubut', value: 'Río Senguer' },
  'robles': { provincia: 'Santiago del Estero', value: 'Robles' },
  'rojas': { provincia: 'Buenos Aires', value: 'Rojas' },
  'roque perez': { provincia: 'Buenos Aires', value: 'Roque Pérez' },
  'rosario': { provincia: 'Santa Fe', value: 'Rosario' },
  'rosario de la frontera': { provincia: 'Salta', value: 'Rosario de la Frontera' },
  'rosario de lerma': { provincia: 'Salta', value: 'Rosario de Lerma' },
  'rosario vera penaloza': { provincia: 'La Rioja', value: 'Rosario Vera Peñaloza' },
  'saavedra': { provincia: 'Buenos Aires', value: 'Saavedra' },
  'saladas': { provincia: 'Corrientes', value: 'Saladas' },
  'saladillo': { provincia: 'Buenos Aires', value: 'Saladillo' },
  'salavina': { provincia: 'Santiago del Estero', value: 'Salavina' },
  'salliquelo': { provincia: 'Buenos Aires', value: 'Salliqueló' },
  'salto': { provincia: 'Buenos Aires', value: 'Salto' },
  'san alberto': { provincia: 'Córdoba', value: 'San Alberto' },
  'san andres de giles': { provincia: 'Buenos Aires', value: 'San Andrés de Giles' },
  'san antonio de areco': { provincia: 'Buenos Aires', value: 'San Antonio de Areco' },
  'san blas de los sauces': { provincia: 'La Rioja', value: 'San Blas de Los Sauces' },
  'san cayetano': { provincia: 'Buenos Aires', value: 'San Cayetano' },
  'san cosme': { provincia: 'Corrientes', value: 'San Cosme' },
  'san cristobal': { provincia: 'Santa Fe', value: 'San Cristóbal' },
  'san ignacio': { provincia: 'Misiones', value: 'San Ignacio' },
  'san isidro': { provincia: 'Buenos Aires', value: 'San Isidro' },
  'san jeronimo': { provincia: 'Santa Fe', value: 'San Jerónimo' },
  'san luis del palmar': { provincia: 'Corrientes', value: 'San Luis del Palmar' },
  'san nicolas': { provincia: 'Buenos Aires', value: 'San Nicolás' },
  'san rafael': { provincia: 'Mendoza', value: 'San Rafael' },
  'san roque': { provincia: 'Corrientes', value: 'San Roque' },
  'san salvador': { provincia: 'Entre Ríos', value: 'San Salvador' },
  'san vicente': { provincia: 'Buenos Aires', value: 'San Vicente' },
  'sanagasta': { provincia: 'La Rioja', value: 'Sanagasta' },
  'santa barbara': { provincia: 'Jujuy', value: 'Santa Bárbara' },
  'santa catalina': { provincia: 'Jujuy', value: 'Santa Catalina' },
  'santa lucia': { provincia: 'San Juan', value: 'Santa Lucía' },
  'santa victoria': { provincia: 'Salta', value: 'Santa Victoria' },
  'santo tome': { provincia: 'Corrientes', value: 'Santo Tomé' },
  'sargento cabral': { provincia: 'Chaco', value: 'Sargento Cabral' },
  'sauce': { provincia: 'Corrientes', value: 'Sauce' },
  'silipica': { provincia: 'Santiago del Estero', value: 'Silípica' },
  'simoca': { provincia: 'Tucumán', value: 'Simoca' },
  'sobremonte': { provincia: 'Córdoba', value: 'Sobremonte' },
  'suipacha': { provincia: 'Buenos Aires', value: 'Suipacha' },
  'susques': { provincia: 'Jujuy', value: 'Susques' },
  'tafi del valle': { provincia: 'Tucumán', value: 'Tafí del Valle' },
  'tafi viejo': { provincia: 'Tucumán', value: 'Tafí Viejo' },
  'tala': { provincia: 'Entre Ríos', value: 'Tala' },
  'tandil': { provincia: 'Buenos Aires', value: 'Tandil' },
  'tapalque': { provincia: 'Buenos Aires', value: 'Tapalqué' },
  'tapenaga': { provincia: 'Chaco', value: 'Tapenagá' },
  'tehuelches': { provincia: 'Chubut', value: 'Tehuelches' },
  'telsen': { provincia: 'Chubut', value: 'Telsen' },
  'tercero arriba': { provincia: 'Córdoba', value: 'Tercero Arriba' },
  'tigre': { provincia: 'Buenos Aires', value: 'Tigre' },
  'tilcara': { provincia: 'Jujuy', value: 'Tilcara' },
  'tinogasta': { provincia: 'Catamarca', value: 'Tinogasta' },
  'toay': { provincia: 'La Pampa', value: 'Toay' },
  'tolhuin': { provincia: 'Tierra del Fuego, Antártida e Islas del Atlántico Sur', value: 'Tolhuin' },
  'tordillo': { provincia: 'Buenos Aires', value: 'Tordillo' },
  'tornquist': { provincia: 'Buenos Aires', value: 'Tornquist' },
  'totoral': { provincia: 'Córdoba', value: 'Totoral' },
  'trancas': { provincia: 'Tucumán', value: 'Trancas' },
  'trenel': { provincia: 'La Pampa', value: 'Trenel' },
  'trenque lauquen': { provincia: 'Buenos Aires', value: 'Trenque Lauquen' },
  'tres arroyos': { provincia: 'Buenos Aires', value: 'Tres Arroyos' },
  'tres de febrero': { provincia: 'Buenos Aires', value: 'Tres de Febrero' },
  'tres lomas': { provincia: 'Buenos Aires', value: 'Tres Lomas' },
  'tulumba': { provincia: 'Córdoba', value: 'Tulumba' },
  'tumbaya': { provincia: 'Jujuy', value: 'Tumbaya' },
  'tunuyan': { provincia: 'Mendoza', value: 'Tunuyán' },
  'tupungato': { provincia: 'Mendoza', value: 'Tupungato' },
  'ullum': { provincia: 'San Juan', value: 'Ullum' },
  'union': { provincia: 'Córdoba', value: 'Unión' },
  'uruguay': { provincia: 'Entre Ríos', value: 'Uruguay' },
  'ushuaia': { provincia: 'Tierra del Fuego, Antártida e Islas del Atlántico Sur', value: 'Ushuaia' },
  'utracan': { provincia: 'La Pampa', value: 'Utracán' },
  'valcheta': { provincia: 'Río Negro', value: 'Valcheta' },
  'valle fertil': { provincia: 'San Juan', value: 'Valle Fértil' },
  'valle grande': { provincia: 'Jujuy', value: 'Valle Grande' },
  'valle viejo': { provincia: 'Catamarca', value: 'Valle Viejo' },
  'vera': { provincia: 'Santa Fe', value: 'Vera' },
  'vicente lopez': { provincia: 'Buenos Aires', value: 'Vicente López' },
  'victoria': { provincia: 'Entre Ríos', value: 'Victoria' },
  'villa gesell': { provincia: 'Buenos Aires', value: 'Villa Gesell' },
  'villaguay': { provincia: 'Entre Ríos', value: 'Villaguay' },
  'villarino': { provincia: 'Buenos Aires', value: 'Villarino' },
  'vinchina': { provincia: 'La Rioja', value: 'Vinchina' },
  'yavi': { provincia: 'Jujuy', value: 'Yavi' },
  'yerba buena': { provincia: 'Tucumán', value: 'Yerba Buena' },
  'zapala': { provincia: 'Neuquén', value: 'Zapala' },
  'zarate': { provincia: 'Buenos Aires', value: 'Zárate' },
  'zonda': { provincia: 'San Juan', value: 'Zonda' },

  // ── Ambiguos (47) — requieren desambiguación ──────────────────────────

  '25 de mayo': [ { provincia: 'Río Negro', value: '25 de Mayo' }, { provincia: 'San Juan', value: '25 de Mayo' }, { provincia: 'Buenos Aires', value: '25 de Mayo' }, { provincia: 'Misiones', value: '25 de Mayo' }, { provincia: 'Chaco', value: '25 de Mayo' } ],
  '9 de julio': [ { provincia: 'Río Negro', value: '9 de Julio' }, { provincia: 'San Juan', value: '9 de Julio' }, { provincia: 'Buenos Aires', value: '9 de Julio' }, { provincia: 'Santa Fe', value: '9 de Julio' }, { provincia: 'Chaco', value: '9 de Julio' } ],
  'adolfo alsina': [ { provincia: 'Buenos Aires', value: 'Adolfo Alsina' }, { provincia: 'Río Negro', value: 'Adolfo Alsina' } ],
  'almirante brown': [ { provincia: 'Chaco', value: 'Almirante Brown' }, { provincia: 'Buenos Aires', value: 'Almirante Brown' } ],
  'avellaneda': [ { provincia: 'Río Negro', value: 'Avellaneda' }, { provincia: 'Santiago del Estero', value: 'Avellaneda' }, { provincia: 'Buenos Aires', value: 'Avellaneda' } ],
  'ayacucho': [ { provincia: 'San Luis', value: 'Ayacucho' }, { provincia: 'Buenos Aires', value: 'Ayacucho' } ],
  'belgrano': [ { provincia: 'San Luis', value: 'Belgrano' }, { provincia: 'Santiago del Estero', value: 'Belgrano' }, { provincia: 'Santa Fe', value: 'Belgrano' } ],
  'bermejo': [ { provincia: 'Formosa', value: 'Bermejo' }, { provincia: 'Chaco', value: 'Bermejo' } ],
  'capital': [ { provincia: 'Salta', value: 'Capital' }, { provincia: 'La Pampa', value: 'Capital' }, { provincia: 'La Rioja', value: 'Capital' }, { provincia: 'Santiago del Estero', value: 'Capital' }, { provincia: 'Misiones', value: 'Capital' }, { provincia: 'Tucumán', value: 'Capital' }, { provincia: 'Corrientes', value: 'Capital' }, { provincia: 'Córdoba', value: 'Capital' }, { provincia: 'Catamarca', value: 'Capital' }, { provincia: 'Mendoza', value: 'Capital' }, { provincia: 'San Juan', value: 'Capital' } ],
  'chacabuco': [ { provincia: 'San Luis', value: 'Chacabuco' }, { provincia: 'Chaco', value: 'Chacabuco' }, { provincia: 'Buenos Aires', value: 'Chacabuco' } ],
  'colon': [ { provincia: 'Buenos Aires', value: 'Colón' }, { provincia: 'Entre Ríos', value: 'Colón' }, { provincia: 'Córdoba', value: 'Colón' } ],
  'concepcion': [ { provincia: 'Misiones', value: 'Concepción' }, { provincia: 'Corrientes', value: 'Concepción' } ],
  'coronel pringles': [ { provincia: 'Buenos Aires', value: 'Coronel Pringles' }, { provincia: 'San Luis', value: 'Coronel Pringles' } ],
  'florentino ameghino': [ { provincia: 'Buenos Aires', value: 'Florentino Ameghino' }, { provincia: 'Chubut', value: 'Florentino Ameghino' } ],
  'general alvear': [ { provincia: 'Buenos Aires', value: 'General Alvear' }, { provincia: 'Corrientes', value: 'General Alvear' }, { provincia: 'Mendoza', value: 'General Alvear' } ],
  'general belgrano': [ { provincia: 'La Rioja', value: 'General Belgrano' }, { provincia: 'Buenos Aires', value: 'General Belgrano' }, { provincia: 'Chaco', value: 'General Belgrano' } ],
  'general guemes': [ { provincia: 'Chaco', value: 'General Güemes' }, { provincia: 'Salta', value: 'General Güemes' } ],
  'general paz': [ { provincia: 'Buenos Aires', value: 'General Paz' }, { provincia: 'Corrientes', value: 'General Paz' } ],
  'general roca': [ { provincia: 'Río Negro', value: 'General Roca' }, { provincia: 'Córdoba', value: 'General Roca' } ],
  'general san martin': [ { provincia: 'Buenos Aires', value: 'General San Martín' }, { provincia: 'La Rioja', value: 'General San Martín' }, { provincia: 'Córdoba', value: 'General San Martín' } ],
  'independencia': [ { provincia: 'La Rioja', value: 'Independencia' }, { provincia: 'Chaco', value: 'Independencia' } ],
  'ituzaingo': [ { provincia: 'Buenos Aires', value: 'Ituzaingó' }, { provincia: 'Corrientes', value: 'Ituzaingó' } ],
  'junin': [ { provincia: 'San Luis', value: 'Junín' }, { provincia: 'Buenos Aires', value: 'Junín' }, { provincia: 'Mendoza', value: 'Junín' } ],
  'la paz': [ { provincia: 'Catamarca', value: 'La Paz' }, { provincia: 'Mendoza', value: 'La Paz' }, { provincia: 'Entre Ríos', value: 'La Paz' } ],
  'lavalle': [ { provincia: 'Corrientes', value: 'Lavalle' }, { provincia: 'Mendoza', value: 'Lavalle' } ],
  'leandro n. alem': [ { provincia: 'Misiones', value: 'Leandro N. Alem' }, { provincia: 'Buenos Aires', value: 'Leandro N. Alem' } ],
  'libertador general san martin': [ { provincia: 'San Luis', value: 'Libertador General San Martín' }, { provincia: 'Misiones', value: 'Libertador General San Martín' }, { provincia: 'Chaco', value: 'Libertador General San Martín' } ],
  'maipu': [ { provincia: 'Buenos Aires', value: 'Maipú' }, { provincia: 'Chaco', value: 'Maipú' }, { provincia: 'Mendoza', value: 'Maipú' } ],
  'mercedes': [ { provincia: 'Buenos Aires', value: 'Mercedes' }, { provincia: 'Corrientes', value: 'Mercedes' } ],
  'minas': [ { provincia: 'Córdoba', value: 'Minas' }, { provincia: 'Neuquén', value: 'Minas' } ],
  'moreno': [ { provincia: 'Buenos Aires', value: 'Moreno' }, { provincia: 'Santiago del Estero', value: 'Moreno' } ],
  'pellegrini': [ { provincia: 'Buenos Aires', value: 'Pellegrini' }, { provincia: 'Santiago del Estero', value: 'Pellegrini' } ],
  'rawson': [ { provincia: 'Chubut', value: 'Rawson' }, { provincia: 'San Juan', value: 'Rawson' } ],
  'rio chico': [ { provincia: 'Santa Cruz', value: 'Río Chico' }, { provincia: 'Tucumán', value: 'Río Chico' } ],
  'rivadavia': [ { provincia: 'Santiago del Estero', value: 'Rivadavia' }, { provincia: 'Salta', value: 'Rivadavia' }, { provincia: 'Buenos Aires', value: 'Rivadavia' }, { provincia: 'Mendoza', value: 'Rivadavia' }, { provincia: 'San Juan', value: 'Rivadavia' } ],
  'san antonio': [ { provincia: 'Río Negro', value: 'San Antonio' }, { provincia: 'Jujuy', value: 'San Antonio' } ],
  'san carlos': [ { provincia: 'Salta', value: 'San Carlos' }, { provincia: 'Mendoza', value: 'San Carlos' } ],
  'san fernando': [ { provincia: 'Buenos Aires', value: 'San Fernando' }, { provincia: 'Chaco', value: 'San Fernando' } ],
  'san javier': [ { provincia: 'Santa Fe', value: 'San Javier' }, { provincia: 'Misiones', value: 'San Javier' }, { provincia: 'Córdoba', value: 'San Javier' } ],
  'san justo': [ { provincia: 'Santa Fe', value: 'San Justo' }, { provincia: 'Córdoba', value: 'San Justo' } ],
  'san lorenzo': [ { provincia: 'Santa Fe', value: 'San Lorenzo' }, { provincia: 'Chaco', value: 'San Lorenzo' } ],
  'san martin': [ { provincia: 'San Juan', value: 'San Martín' }, { provincia: 'Santiago del Estero', value: 'San Martín' }, { provincia: 'Santa Fe', value: 'San Martín' }, { provincia: 'Corrientes', value: 'San Martín' }, { provincia: 'Mendoza', value: 'San Martín' } ],
  'san miguel': [ { provincia: 'Buenos Aires', value: 'San Miguel' }, { provincia: 'Corrientes', value: 'San Miguel' } ],
  'san pedro': [ { provincia: 'Jujuy', value: 'San Pedro' }, { provincia: 'Misiones', value: 'San Pedro' }, { provincia: 'Buenos Aires', value: 'San Pedro' } ],
  'santa maria': [ { provincia: 'Córdoba', value: 'Santa María' }, { provincia: 'Catamarca', value: 'Santa María' } ],
  'santa rosa': [ { provincia: 'Mendoza', value: 'Santa Rosa' }, { provincia: 'Catamarca', value: 'Santa Rosa' } ],
  'sarmiento': [ { provincia: 'San Juan', value: 'Sarmiento' }, { provincia: 'Santiago del Estero', value: 'Sarmiento' }, { provincia: 'Chubut', value: 'Sarmiento' } ],

};
