/**
 * geo_maps/uy/municipios.js
 *
 * Normalización de nombres de municipios de Uruguay.
 * Generado desde el WFS de IGM Uruguay (LimitesMunicipales250:LimitesMunicipales).
 * Total: 129 features → 127 únicos, 0 ambiguos.
 *
 * Estructura:
 *   - Entrada única   → { value }                    (sin ambigüedad)
 *   - Entrada ambigua → [{ value }, ...]             (requiere desambiguación)
 *
 * Usado por GEO_MAPS en geo_maps/index.js.
 */

export const MUNICIPIOS_MAP_UY = {

  // ── Únicos (127) ─────────────────────────────────────────────────

  '18 de mayo': { value: '18 DE MAYO' },
  'a': { value: 'A' },
  'acegua': { value: 'ACEGUÁ' },
  'aguas corrientes': { value: 'AGUAS CORRIENTES' },
  'aigua': { value: 'AIGUÁ' },
  'ansina': { value: 'ANSINA' },
  'arbolito': { value: 'ARBOLITO' },
  'arevalo': { value: 'ARÉVALO' },
  'atlantida': { value: 'ATLÁNTIDA' },
  'b': { value: 'B' },
  'baltasar brum': { value: 'BALTASAR BRUM' },
  'banado de medina': { value: 'BAÑADO DE MEDINA' },
  'barros blancos': { value: 'BARROS BLANCOS' },
  'belen': { value: 'BELÉN' },
  'bella union': { value: 'BELLA UNIÓN' },
  'c': { value: 'C' },
  'canelones': { value: 'CANELONES' },
  'cardona': { value: 'CARDONA' },
  'carmelo': { value: 'CARMELO' },
  'castillos': { value: 'CASTILLOS' },
  'casupa': { value: 'CASUPÁ' },
  'centurion': { value: 'CENTURIÓN' },
  'cerro chato': { value: 'CERRO CHATO' },
  'cerro de las cuentas': { value: 'CERRO DE LAS CUENTAS' },
  'ch': { value: 'CH' },
  'chapicuy': { value: 'CHAPICUY' },
  'chuy': { value: 'CHUY' },
  'ciudad de la costa': { value: 'CIUDAD DE LA COSTA' },
  'ciudad del plata': { value: 'CIUDAD DEL PLATA' },
  'colonia lavalleja': { value: 'COLONIA LAVALLEJA' },
  'colonia nicoch': { value: 'COLONIA NICOCH' },
  'colonia valdense': { value: 'COLONIA VALDENSE' },
  'conchillas': { value: 'CONCHILLAS' },
  'cufre': { value: 'CUFRÉ' },
  'd': { value: 'D' },
  'dolores': { value: 'DOLORES' },
  'e': { value: 'E' },
  'ecilda paullier': { value: 'ECILDA PAULLIER' },
  'empalme olmos': { value: 'EMPALME OLMOS' },
  'f': { value: 'F' },
  'florencio sanchez': { value: 'FLORENCIO SÁNCHEZ' },
  'fraile muerto': { value: 'FRAILE MUERTO' },
  'fray marcos': { value: 'FRAY MARCOS' },
  'g': { value: 'G' },
  'garzon': { value: 'GARZÓN' },
  'general enrique martinez': { value: 'GENERAL ENRIQUE MARTÍNEZ' },
  'guichon': { value: 'GUICHÓN' },
  'isidoro noblia': { value: 'ISIDORO NOBLÍA' },
  'ismael cortinas': { value: 'ISMAEL CORTINAS' },
  'jose batlle y ordonez': { value: 'JOSÉ BATLLE Y ORDÓÑEZ' },
  'jose enrique rodo': { value: 'JOSÉ ENRIQUE RODÓ' },
  'jose pedro varela': { value: 'JOSÉ PEDRO VARELA' },
  'juan lacaze': { value: 'JUAN LACAZE' },
  'la floresta': { value: 'LA FLORESTA' },
  'la paloma': { value: 'LA PALOMA' },
  'la paz': { value: 'LA PAZ' },
  'la paz cp': { value: 'LA PAZ CP' },
  'laguna merin': { value: 'LAGUNA MERÍN' },
  'las canas': { value: 'LAS CAÑAS' },
  'las piedras': { value: 'LAS PIEDRAS' },
  'lascano': { value: 'LASCANO' },
  'libertad': { value: 'LIBERTAD' },
  'lorenzo geyres': { value: 'LORENZO GEYRES' },
  'los cerrillos': { value: 'LOS CERRILLOS' },
  'maldonado': { value: 'MALDONADO' },
  'mataojo': { value: 'MATAOJO' },
  'miguelete': { value: 'MIGUELETE' },
  'migues': { value: 'MIGUES' },
  'minas de corrales': { value: 'MINAS DE CORRALES' },
  'montes': { value: 'MONTES' },
  'nueva helvecia': { value: 'NUEVA HELVECIA' },
  'nueva palmira': { value: 'NUEVA PALMIRA' },
  'nuevo berlin': { value: 'NUEVO BERLÍN' },
  'ombues de lavalle': { value: 'OMBÚES DE LAVALLE' },
  'palmitas': { value: 'PALMITAS' },
  'pan de azucar': { value: 'PAN DE AZUCAR' },
  'pando': { value: 'PANDO' },
  'parque del plata': { value: 'PARQUE DEL PLATA' },
  'paso carrasco': { value: 'PASO CARRASCO' },
  'paso de los toros': { value: 'PASO DE LOS TOROS' },
  'piedras coloradas': { value: 'PIEDRAS COLORADAS' },
  'piriapolis': { value: 'PIRIÁPOLIS' },
  'placido rosas': { value: 'PLÁCIDO ROSAS' },
  'porvenir': { value: 'PORVENIR' },
  'progreso': { value: 'PROGRESO' },
  'punta del este': { value: 'PUNTA DEL ESTE' },
  'quebracho': { value: 'QUEBRACHO' },
  'ramon trigo': { value: 'RAMÓN TRIGO' },
  'rincon': { value: 'RINCÓN' },
  'rio branco': { value: 'RIO BRANCO' },
  'rodriguez': { value: 'RODRIGUEZ' },
  'rosario': { value: 'ROSARIO' },
  'salinas': { value: 'SALINAS' },
  'san antonio': { value: 'SAN ANTONIO' },
  'san bautista': { value: 'SAN BAUTISTA' },
  'san carlos': { value: 'SAN CARLOS' },
  'san gregorio de polanco': { value: 'SAN GREGORIO DE POLANCO' },
  'san jacinto': { value: 'SAN JACINTO' },
  'san javier': { value: 'SAN JAVIER' },
  'san ramon': { value: 'SAN RAMÓN' },
  'santa clara de olimar': { value: 'SANTA CLARA DE OLIMAR' },
  'santa lucia': { value: 'SANTA LUCÍA' },
  'santa rosa': { value: 'SANTA ROSA' },
  'sarandi del yi': { value: 'SARANDÍ DEL YÍ' },
  'sarandi grande': { value: 'SARANDÍ GRANDE' },
  'sauce': { value: 'SAUCE' },
  'soca': { value: 'SOCA' },
  'solis de mataojo': { value: 'SOLÍS DE MATAOJO' },
  'solis grande': { value: 'SOLÍS GRANDE' },
  'suarez': { value: 'SUÁREZ' },
  'tala': { value: 'TALA' },
  'tambores': { value: 'TAMBORES' },
  'tarariras': { value: 'TARARIRAS' },
  'toledo': { value: 'TOLEDO' },
  'tomas gomensoro': { value: 'TOMÁS GOMENSORO' },
  'tranqueras': { value: 'TRANQUERAS' },
  'tres islas': { value: 'TRES ISLAS' },
  'tupambae': { value: 'TUPAMBAÉ' },
  'valentin': { value: 'VALENTÍN' },
  'vergara': { value: 'VERGARA' },
  'vichadero': { value: 'VICHADERO' },
  'villa caraguata': { value: 'VILLA CARAGUATÁ' },
  'villa constitucion': { value: 'VILLA CONSTITUCIÓN' },
  'villa del carmen': { value: 'VILLA DEL CARMEN' },
  'villa mariscala': { value: 'VILLA MARISCALA' },
  'villa sara': { value: 'VILLA SARA' },
  'young': { value: 'YOUNG' },

};