/**
 * geo_maps/cl/comunas.js
 *
 * Normalización de nombres de comunas chilenas.
 * Mapea texto del usuario (normalizado, sin tildes) → valor exacto en el WFS del MOP.
 *
 * Campo de referencia: NOM_COM en MAPA_BASE/LIMITES/MapServer/2
 * Valores en MAYÚSCULAS — normalizar al consultar.
 * Total: 346 comunas.
 *
 * Usado por GEO_MAPS en geo_maps/index.js.
 */

export const COMUNAS_MAP_CL = {
  "algarrobo": { value: "ALGARROBO" },
  "alhue": { value: "ALHUE" },
  "alto bio bio": { value: "ALTO BIO BIO" },
  "alto biobio": { value: "ALTO BIO BIO" },
  "alto del carmen": { value: "ALTO DEL CARMEN" },
  "alto hospicio": { value: "ALTO HOSPICIO" },
  "ancud": { value: "ANCUD" },
  "andacollo": { value: "ANDACOLLO" },
  "angol": { value: "ANGOL" },
  "antartica": { value: "ANTARTICA" },
  "antofagasta": { value: "ANTOFAGASTA" },
  "antuco": { value: "ANTUCO" },
  "arauco": { value: "ARAUCO" },
  "arica": { value: "ARICA" },
  "aysen": { value: "AYSEN" },
  "buin": { value: "BUIN" },
  "bulnes": { value: "BULNES" },
  "cabildo": { value: "CABILDO" },
  "cabo de hornos": { value: "CABO DE HORNOS" },
  "cabrero": { value: "CABRERO" },
  "calama": { value: "CALAMA" },
  "calbuco": { value: "CALBUCO" },
  "caldera": { value: "CALDERA" },
  "calera": { value: "CALERA" },
  "calera de tango": { value: "CALERA DE TANGO" },
  "calle larga": { value: "CALLE LARGA" },
  "camarones": { value: "CAMARONES" },
  "camina": { value: "CAMINA" },
  "canela": { value: "CANELA" },
  "canete": { value: "CANETE" },
  "carahue": { value: "CARAHUE" },
  "cartagena": { value: "CARTAGENA" },
  "casablanca": { value: "CASABLANCA" },
  "castro": { value: "CASTRO" },
  "catemu": { value: "CATEMU" },
  "cauquenes": { value: "CAUQUENES" },
  "cerrillos": { value: "CERRILLOS" },
  "cerro navia": { value: "CERRO NAVIA" },
  "chaiten": { value: "CHAITEN" },
  "chanaral": { value: "CHANARAL" },
  "chanco": { value: "CHANCO" },
  "chepica": { value: "CHEPICA" },
  "chiguayante": { value: "CHIGUAYANTE" },
  "chile chico": { value: "CHILE CHICO" },
  "chillan": { value: "CHILLAN" },
  "chillan viejo": { value: "CHILLAN VIEJO" },
  "chimbarongo": { value: "CHIMBARONGO" },
  "chol chol": { value: "CHOL CHOL" },
  "chonchi": { value: "CHONCHI" },
  "cisnes": { value: "CISNES" },
  "cobquecura": { value: "COBQUECURA" },
  "cochamo": { value: "COCHAMO" },
  "cochrane": { value: "COCHRANE" },
  "codegua": { value: "CODEGUA" },
  "coelemu": { value: "COELEMU" },
  "coihayque": { value: "COIHAYQUE" },
  "coihueco": { value: "COIHUECO" },
  "coinco": { value: "COINCO" },
  "colbun": { value: "COLBUN" },
  "colchane": { value: "COLCHANE" },
  "colina": { value: "COLINA" },
  "collipulli": { value: "COLLIPULLI" },
  "coltauco": { value: "COLTAUCO" },
  "combarbala": { value: "COMBARBALA" },
  "con con": { value: "CON CON" },
  "concepcion": { value: "CONCEPCION" },
  "conchali": { value: "CONCHALI" },
  "constitucion": { value: "CONSTITUCION" },
  "contulmo": { value: "CONTULMO" },
  "copiapo": { value: "COPIAPO" },
  "coquimbo": { value: "COQUIMBO" },
  "coronel": { value: "CORONEL" },
  "corral": { value: "CORRAL" },
  "cunco": { value: "CUNCO" },
  "curacautin": { value: "CURACAUTIN" },
  "curacavi": { value: "CURACAVI" },
  "curaco de velez": { value: "CURACO DE VELEZ" },
  "curanilahue": { value: "CURANILAHUE" },
  "curarrehue": { value: "CURARREHUE" },
  "curepto": { value: "CUREPTO" },
  "curico": { value: "CURICO" },
  "dalcahue": { value: "DALCAHUE" },
  "diego de almagro": { value: "DIEGO DE ALMAGRO" },
  "donihue": { value: "DONIHUE" },
  "el bosque": { value: "EL BOSQUE" },
  "el carmen": { value: "EL CARMEN" },
  "el monte": { value: "EL MONTE" },
  "el olivar": { value: "EL OLIVAR" },
  "el quisco": { value: "EL QUISCO" },
  "el tabo": { value: "EL TABO" },
  "empedrado": { value: "EMPEDRADO" },
  "ercilla": { value: "ERCILLA" },
  "estacion central": { value: "ESTACION CENTRAL" },
  "florida": { value: "FLORIDA" },
  "freire": { value: "FREIRE" },
  "freirina": { value: "FREIRINA" },
  "fresia": { value: "FRESIA" },
  "frutillar": { value: "FRUTILLAR" },
  "futaleufu": { value: "FUTALEUFU" },
  "futrono": { value: "FUTRONO" },
  "galvarino": { value: "GALVARINO" },
  "gorbea": { value: "GORBEA" },
  "gral. lagos": { value: "GRAL. LAGOS" },
  "general lagos": { value: "GRAL. LAGOS" },
  "graneros": { value: "GRANEROS" },
  "guaitecas": { value: "GUAITECAS" },
  "hijuelas": { value: "HIJUELAS" },
  "hualaihue": { value: "HUALAIHUE" },
  "hualane": { value: "HUALANE" },
  "hualpen": { value: "HUALPEN" },
  "hualqui": { value: "HUALQUI" },
  "huara": { value: "HUARA" },
  "huasco": { value: "HUASCO" },
  "huechuraba": { value: "HUECHURABA" },
  "illapel": { value: "ILLAPEL" },
  "independencia": { value: "INDEPENDENCIA" },
  "iquique": { value: "IQUIQUE" },
  "isla de maipo": { value: "ISLA DE MAIPO" },
  "isla de pascua": { value: "ISLA DE PASCUA" },
  "juan fernandez": { value: "JUAN FERNANDEZ" },
  "la cisterna": { value: "LA CISTERNA" },
  "la cruz": { value: "LA CRUZ" },
  "la estrella": { value: "LA ESTRELLA" },
  "la florida": { value: "LA FLORIDA" },
  "la granja": { value: "LA GRANJA" },
  "la higuera": { value: "LA HIGUERA" },
  "la ligua": { value: "LA LIGUA" },
  "la pintana": { value: "LA PINTANA" },
  "la reina": { value: "LA REINA" },
  "la serena": { value: "LA SERENA" },
  "la union": { value: "LA UNION" },
  "lago ranco": { value: "LAGO RANCO" },
  "lago verde": { value: "LAGO VERDE" },
  "laguna blanca": { value: "LAGUNA BLANCA" },
  "laja": { value: "LAJA" },
  "lampa": { value: "LAMPA" },
  "lanco": { value: "LANCO" },
  "las cabras": { value: "LAS CABRAS" },
  "las condes": { value: "LAS CONDES" },
  "lautaro": { value: "LAUTARO" },
  "lebu": { value: "LEBU" },
  "licanten": { value: "LICANTEN" },
  "limache": { value: "LIMACHE" },
  "linares": { value: "LINARES" },
  "litueche": { value: "LITUECHE" },
  "llaillay": { value: "LLAILLAY" },
  "llanquihue": { value: "LLANQUIHUE" },
  "lo barnechea": { value: "LO BARNECHEA" },
  "lo espejo": { value: "LO ESPEJO" },
  "lo prado": { value: "LO PRADO" },
  "lolol": { value: "LOLOL" },
  "loncoche": { value: "LONCOCHE" },
  "longavi": { value: "LONGAVI" },
  "lonquimay": { value: "LONQUIMAY" },
  "los alamos": { value: "LOS ALAMOS" },
  "los andes": { value: "LOS ANDES" },
  "los angeles": { value: "LOS ANGELES" },
  "los lagos": { value: "LOS LAGOS" },
  "los muermos": { value: "LOS MUERMOS" },
  "los sauces": { value: "LOS SAUCES" },
  "los vilos": { value: "LOS VILOS" },
  "lota": { value: "LOTA" },
  "lumaco": { value: "LUMACO" },
  "machali": { value: "MACHALI" },
  "macul": { value: "MACUL" },
  "mafil": { value: "MAFIL" },
  "maipu": { value: "MAIPU" },
  "malloa": { value: "MALLOA" },
  "marchihue": { value: "MARCHIHUE" },
  "maria elena": { value: "MARIA ELENA" },
  "maria pinto": { value: "MARIA PINTO" },
  "mariquina": { value: "MARIQUINA" },
  "maule": { value: "MAULE" },
  "maullin": { value: "MAULLIN" },
  "mejillones": { value: "MEJILLONES" },
  "melipeuco": { value: "MELIPEUCO" },
  "melipilla": { value: "MELIPILLA" },
  "molina": { value: "MOLINA" },
  "monte patria": { value: "MONTE PATRIA" },
  "mostazal": { value: "MOSTAZAL" },
  "mulchen": { value: "MULCHEN" },
  "nacimiento": { value: "NACIMIENTO" },
  "nancagua": { value: "NANCAGUA" },
  "natales": { value: "NATALES" },
  "navidad": { value: "NAVIDAD" },
  "negrete": { value: "NEGRETE" },
  "ninhue": { value: "NINHUE" },
  "niquen": { value: "NIQUEN" },
  "nogales": { value: "NOGALES" },
  "nueva imperial": { value: "NUEVA IMPERIAL" },
  "nunoa": { value: "NUNOA" },
  "ohiggins": { value: "OHIGGINS" },
  "ollague": { value: "OLLAGUE" },
  "olmue": { value: "OLMUE" },
  "osorno": { value: "OSORNO" },
  "ovalle": { value: "OVALLE" },
  "padre hurtado": { value: "PADRE HURTADO" },
  "padre las casas": { value: "PADRE LAS CASAS" },
  "paiguano": { value: "PAIGUANO" },
  "paillaco": { value: "PAILLACO" },
  "paine": { value: "PAINE" },
  "palena": { value: "PALENA" },
  "palmilla": { value: "PALMILLA" },
  "panguipulli": { value: "PANGUIPULLI" },
  "panquehue": { value: "PANQUEHUE" },
  "papudo": { value: "PAPUDO" },
  "paredones": { value: "PAREDONES" },
  "parral": { value: "PARRAL" },
  "pedro aguirre cerda": { value: "PEDRO AGUIRRE CERDA" },
  "pelarco": { value: "PELARCO" },
  "pelluhue": { value: "PELLUHUE" },
  "pemuco": { value: "PEMUCO" },
  "penaflor": { value: "PENAFLOR" },
  "penalolen": { value: "PENALOLEN" },
  "pencahue": { value: "PENCAHUE" },
  "penco": { value: "PENCO" },
  "peralillo": { value: "PERALILLO" },
  "perquenco": { value: "PERQUENCO" },
  "petorca": { value: "PETORCA" },
  "peumo": { value: "PEUMO" },
  "pica": { value: "PICA" },
  "pichidegua": { value: "PICHIDEGUA" },
  "pichilemu": { value: "PICHILEMU" },
  "pinto": { value: "PINTO" },
  "pirque": { value: "PIRQUE" },
  "pitrufquen": { value: "PITRUFQUEN" },
  "placilla": { value: "PLACILLA" },
  "portezuelo": { value: "PORTEZUELO" },
  "porvenir": { value: "PORVENIR" },
  "pozo almonte": { value: "POZO ALMONTE" },
  "primavera": { value: "PRIMAVERA" },
  "providencia": { value: "PROVIDENCIA" },
  "puchuncavi": { value: "PUCHUNCAVI" },
  "pucon": { value: "PUCON" },
  "pudahuel": { value: "PUDAHUEL" },
  "puente alto": { value: "PUENTE ALTO" },
  "puerto montt": { value: "PUERTO MONTT" },
  "puerto octay": { value: "PUERTO OCTAY" },
  "puerto varas": { value: "PUERTO VARAS" },
  "pumanque": { value: "PUMANQUE" },
  "punitaqui": { value: "PUNITAQUI" },
  "punta arenas": { value: "PUNTA ARENAS" },
  "puqueldon": { value: "PUQUELDON" },
  "puren": { value: "PUREN" },
  "purranque": { value: "PURRANQUE" },
  "putaendo": { value: "PUTAENDO" },
  "putre": { value: "PUTRE" },
  "puyehue": { value: "PUYEHUE" },
  "queilen": { value: "QUEILEN" },
  "quellon": { value: "QUELLON" },
  "quemchi": { value: "QUEMCHI" },
  "quilaco": { value: "QUILACO" },
  "quilicura": { value: "QUILICURA" },
  "quilleco": { value: "QUILLECO" },
  "quillon": { value: "QUILLON" },
  "quillota": { value: "QUILLOTA" },
  "quilpue": { value: "QUILPUE" },
  "quinchao": { value: "QUINCHAO" },
  "quinta de tilcoco": { value: "QUINTA DE TILCOCO" },
  "quinta normal": { value: "QUINTA NORMAL" },
  "quintero": { value: "QUINTERO" },
  "quirihue": { value: "QUIRIHUE" },
  "rancagua": { value: "RANCAGUA" },
  "ranquil": { value: "RANQUIL" },
  "rauco": { value: "RAUCO" },
  "recoleta": { value: "RECOLETA" },
  "renaico": { value: "RENAICO" },
  "renca": { value: "RENCA" },
  "rengo": { value: "RENGO" },
  "requinoa": { value: "REQUINOA" },
  "retiro": { value: "RETIRO" },
  "rinconada": { value: "RINCONADA" },
  "rio bueno": { value: "RIO BUENO" },
  "rio claro": { value: "RIO CLARO" },
  "rio hurtado": { value: "RIO HURTADO" },
  "rio ibanez": { value: "RIO IBANEZ" },
  "rio negro": { value: "RIO NEGRO" },
  "rio verde": { value: "RIO VERDE" },
  "romeral": { value: "ROMERAL" },
  "saavedra": { value: "SAAVEDRA" },
  "sagrada familia": { value: "SAGRADA FAMILIA" },
  "salamanca": { value: "SALAMANCA" },
  "san antonio": { value: "SAN ANTONIO" },
  "san bernardo": { value: "SAN BERNARDO" },
  "san carlos": { value: "SAN CARLOS" },
  "san clemente": { value: "SAN CLEMENTE" },
  "san esteban": { value: "SAN ESTEBAN" },
  "san fabian": { value: "SAN FABIAN" },
  "san felipe": { value: "SAN FELIPE" },
  "san fernando": { value: "SAN FERNANDO" },
  "san gregorio": { value: "SAN GREGORIO" },
  "san ignacio": { value: "SAN IGNACIO" },
  "san javier": { value: "SAN JAVIER" },
  "san joaquin": { value: "SAN JOAQUIN" },
  "san jose de maipo": { value: "SAN JOSE DE MAIPO" },
  "san juan de la costa": { value: "SAN JUAN DE LA COSTA" },
  "san miguel": { value: "SAN MIGUEL" },
  "san nicolas": { value: "SAN NICOLAS" },
  "san pablo": { value: "SAN PABLO" },
  "san pedro": { value: "SAN PEDRO" },
  "san pedro de atacama": { value: "SAN PEDRO DE ATACAMA" },
  "san pedro de la paz": { value: "SAN PEDRO DE LA PAZ" },
  "san rafael": { value: "SAN RAFAEL" },
  "san ramon": { value: "SAN RAMON" },
  "san rosendo": { value: "SAN ROSENDO" },
  "san vicente": { value: "SAN VICENTE" },
  "santa barbara": { value: "SANTA BARBARA" },
  "santa cruz": { value: "SANTA CRUZ" },
  "santa juana": { value: "SANTA JUANA" },
  "santiago": { value: "SANTIAGO" },
  "sierra gorda": { value: "SIERRA GORDA" },
  "sta. maria": { value: "STA. MARIA" },
  "santa maria": { value: "STA. MARIA" },
  "sto. domingo": { value: "STO. DOMINGO" },
  "santo domingo": { value: "STO. DOMINGO" },
  "tal tal": { value: "TAL TAL" },
  "talagante": { value: "TALAGANTE" },
  "talca": { value: "TALCA" },
  "talcahuano": { value: "TALCAHUANO" },
  "temuco": { value: "TEMUCO" },
  "teno": { value: "TENO" },
  "teodoro schmidt": { value: "TEODORO SCHMIDT" },
  "tierra amarilla": { value: "TIERRA AMARILLA" },
  "til til": { value: "TIL TIL" },
  "timaukel": { value: "TIMAUKEL" },
  "tirua": { value: "TIRUA" },
  "tocopilla": { value: "TOCOPILLA" },
  "tolten": { value: "TOLTEN" },
  "tome": { value: "TOME" },
  "torres del paine": { value: "TORRES DEL PAINE" },
  "tortel": { value: "TORTEL" },
  "traiguen": { value: "TRAIGUEN" },
  "treguaco": { value: "TREGUACO" },
  "tucapel": { value: "TUCAPEL" },
  "valdivia": { value: "VALDIVIA" },
  "vallenar": { value: "VALLENAR" },
  "valparaiso": { value: "VALPARAISO" },
  "vichuquen": { value: "VICHUQUEN" },
  "victoria": { value: "VICTORIA" },
  "vicuna": { value: "VICUNA" },
  "vilcun": { value: "VILCUN" },
  "villa alegre": { value: "VILLA ALEGRE" },
  "villa alemana": { value: "VILLA ALEMANA" },
  "villarrica": { value: "VILLARRICA" },
  "vina del mar": { value: "VINA DEL MAR" },
  "vitacura": { value: "VITACURA" },
  "yerbas buenas": { value: "YERBAS BUENAS" },
  "yumbel": { value: "YUMBEL" },
  "yungay": { value: "YUNGAY" },
  "zapallar": { value: "ZAPALLAR" }
};
